# Generated by Django 4.2.29 on 2026-03-18 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial_ai_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aianalysis',
            new_name='ai_analysis_patient_34fc39_idx',
            old_name='ai_analysis_patient_created_idx',
        ),
        migrations.RenameIndex(
            model_name='aianalysis',
            new_name='ai_analysis_hospita_dc093a_idx',
            old_name='ai_analysis_hospital_created_idx',
        ),
        migrations.RenameIndex(
            model_name='aianalysis',
            new_name='ai_analysis_analysi_c6dd09_idx',
            old_name='ai_analysis_type_created_idx',
        ),
        migrations.RenameIndex(
            model_name='aianalysiscounter',
            new_name='ai_analysis_hospita_54347b_idx',
            old_name='ai_counter_hospital_date_idx',
        ),
        migrations.RenameIndex(
            model_name='diagnosissuggestion',
            new_name='diagnosis_s_analysi_f07169_idx',
            old_name='diagnosis_analysis_rank_idx',
        ),
        migrations.RenameIndex(
            model_name='diseaseriskprediction',
            new_name='disease_ris_analysi_c5e6cf_idx',
            old_name='disease_risk_analysis_score_idx',
        ),
        migrations.RenameIndex(
            model_name='patientsimilaritymatch',
            new_name='patient_sim_analysi_e000ea_idx',
            old_name='similarity_analysis_rank_idx',
        ),
        migrations.RenameIndex(
            model_name='patientsimilaritymatch',
            new_name='patient_sim_similar_6b1381_idx',
            old_name='similarity_similar_patient_idx',
        ),
        migrations.RenameIndex(
            model_name='referralrecommendation',
            new_name='referral_re_analysi_c3461d_idx',
            old_name='referral_analysis_rank_idx',
        ),
        migrations.RenameIndex(
            model_name='referralrecommendation',
            new_name='referral_re_recomme_d2602c_idx',
            old_name='referral_hospital_idx',
        ),
    ]
