# Generated by Django 4.2.29 on 2026-04-06 11:13

import api.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auditlog_audit_resource_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_ai_analysis_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchImportItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('processing', 'Processing'), ('created', 'Created'), ('validation_error', 'Validation Error'), ('processing_error', 'Processing Error'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(max_length=50)),
                ('ward_id', models.UUIDField(blank=True, null=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('created_user_id', models.UUIDField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'batch_import_item',
                'ordering': ['row_number'],
            },
        ),
        migrations.CreateModel(
            name='BatchImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validating', 'Validating'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused', 'Paused')], default='pending', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('processed_count', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('validation_error_count', models.IntegerField(default=0)),
                ('processing_error_count', models.IntegerField(default=0)),
                ('validation_summary', models.JSONField(blank=True, default=dict, help_text='Summary of validation errors')),
                ('processing_errors', models.JSONField(blank=True, default=list, help_text='List of processing errors')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'batch_import_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkInvitationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('invitation_token', models.CharField(blank=True, max_length=255, unique=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by_user_id', models.UUIDField(blank=True, null=True)),
                ('delivery_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bulk_invitation_item',
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='BulkInvitationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sending', 'Sending'), ('sent', 'Sent'), ('partial', 'Partially Sent'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('total_invitations', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('accepted_count', models.IntegerField(default=0)),
                ('expired_count', models.IntegerField(default=0)),
                ('invitation_expiry_days', models.IntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bulk_invitation_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='aianalysisjob',
            new_name='api_ai_anal_patient_7ea8d8_idx',
            old_name='api_ai_patient_created_idx',
        ),
        migrations.RenameIndex(
            model_name='aianalysisjob',
            new_name='api_ai_anal_hospita_b7daf5_idx',
            old_name='api_ai_hospital_created_idx',
        ),
        migrations.RenameIndex(
            model_name='aianalysisjob',
            new_name='api_ai_anal_status_4a9ce4_idx',
            old_name='api_ai_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='aianalysisjob',
            new_name='api_ai_anal_celery__95e559_idx',
            old_name='api_ai_celery_task_idx',
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='additional_context',
            field=models.JSONField(blank=True, default=api.models._default_dict),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='agents_executed',
            field=models.JSONField(blank=True, default=api.models._default_list, help_text='Names of AI agents that executed'),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='alerts',
            field=models.JSONField(default=api.models._default_list, help_text='Clinical alerts generated'),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='recommended_actions',
            field=models.JSONField(default=api.models._default_list, help_text='List of recommended clinical actions'),
        ),
        migrations.AlterField(
            model_name='diagnosissuggestion',
            name='matching_symptoms',
            field=models.JSONField(blank=True, default=api.models._default_list),
        ),
        migrations.AlterField(
            model_name='diagnosissuggestion',
            name='recommended_tests',
            field=models.JSONField(blank=True, default=api.models._default_list),
        ),
        migrations.AlterField(
            model_name='diseaseriskprediction',
            name='contributing_factors',
            field=models.JSONField(blank=True, default=api.models._default_list, help_text='List of factors that contributed to this prediction'),
        ),
        migrations.AlterField(
            model_name='diseaseriskprediction',
            name='recommendations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=api.models._default_list, help_text='Clinical recommendations for this disease', size=None),
        ),
        migrations.AlterField(
            model_name='patientsimilaritymatch',
            name='matching_conditions',
            field=models.JSONField(blank=True, default=api.models._default_list),
        ),
        migrations.AlterField(
            model_name='triageassessment',
            name='indicators',
            field=models.JSONField(blank=True, default=api.models._default_list, help_text='List of indicators that determined triage level'),
        ),
        migrations.AddField(
            model_name='bulkinvitationjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_invitation_jobs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bulkinvitationjob',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_invitation_jobs', to='core.hospital'),
        ),
        migrations.AddField(
            model_name='bulkinvitationitem',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='api.bulkinvitationjob'),
        ),
        migrations.AddField(
            model_name='batchimportjob',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_import_jobs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchimportjob',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_import_jobs', to='core.hospital'),
        ),
        migrations.AddField(
            model_name='batchimportitem',
            name='batch_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.batchimportjob'),
        ),
        migrations.AddIndex(
            model_name='bulkinvitationjob',
            index=models.Index(fields=['hospital', '-created_at'], name='bulk_invita_hospita_bc0abd_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkinvitationjob',
            index=models.Index(fields=['status', '-created_at'], name='bulk_invita_status_bbcb21_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkinvitationitem',
            index=models.Index(fields=['campaign', 'status'], name='bulk_invita_campaig_3a6455_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkinvitationitem',
            index=models.Index(fields=['expires_at'], name='bulk_invita_expires_47adc3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bulkinvitationitem',
            unique_together={('campaign', 'email')},
        ),
        migrations.AddIndex(
            model_name='batchimportjob',
            index=models.Index(fields=['hospital', '-created_at'], name='batch_impor_hospita_731c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='batchimportjob',
            index=models.Index(fields=['status', '-created_at'], name='batch_impor_status_6ca068_idx'),
        ),
        migrations.AddIndex(
            model_name='batchimportitem',
            index=models.Index(fields=['batch_job', 'status'], name='batch_impor_batch_j_836eb3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batchimportitem',
            unique_together={('batch_job', 'row_number')},
        ),
    ]
