# Generated by Django 4.2.29 on 2026-04-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_batchimportitem_batchimportjob_bulkinvitationitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysis',
            name='analysis_type',
            field=models.CharField(choices=[('comprehensive', 'Comprehensive Multi-Agent Analysis'), ('risk_prediction', 'Disease Risk Prediction'), ('clinical_decision_support', 'Clinical Decision Support'), ('triage', 'Patient Triage'), ('similarity_search', 'Similar Patient Search'), ('referral', 'Hospital Referral Recommendation'), ('differentials', 'Differential Diagnosis'), ('encounter_summary', 'Encounter Summary'), ('discharge_summary', 'Discharge Summary'), ('readmission_risk', 'Readmission Risk'), ('icd10_suggest', 'ICD-10 Suggestion'), ('ward_forecast', 'Ward Bed Forecast')], default='comprehensive', max_length=50),
        ),
        migrations.AlterField(
            model_name='aianalysisjob',
            name='analysis_type',
            field=models.CharField(choices=[('comprehensive', 'Comprehensive Multi-Agent Analysis'), ('risk_prediction', 'Disease Risk Prediction'), ('clinical_decision_support', 'Clinical Decision Support'), ('triage', 'Patient Triage'), ('similarity_search', 'Similar Patient Search'), ('referral', 'Hospital Referral Recommendation'), ('differentials', 'Differential Diagnosis'), ('encounter_summary', 'Encounter Summary'), ('discharge_summary', 'Discharge Summary'), ('readmission_risk', 'Readmission Risk'), ('icd10_suggest', 'ICD-10 Suggestion'), ('ward_forecast', 'Ward Bed Forecast')], max_length=50),
        ),
    ]
