# Generated by Django 4.2.29 on 2026-04-20 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_ai_deployment_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_alter_aianalysis_analysis_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIDeploymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False, help_text='Is clinical AI currently enabled for this hospital?')),
                ('enabled_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('disabled_at', models.DateTimeField(blank=True, help_text='When AI was disabled (if applicable)', null=True)),
                ('model_version', models.CharField(default='1.0.0-placeholder', help_text='Version of model being deployed (e.g., 1.0.0-mimic-iv or 1.1.0-ghana-data)', max_length=50)),
                ('validation_metrics', models.JSONField(blank=True, default=dict, help_text='Model performance metrics: AUC-ROC, sensitivity, specificity per disease')),
                ('approval_notes', models.TextField(blank=True, help_text='Hospital admin notes on approval (why approved, any caveats, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled_by', models.ForeignKey(help_text='Hospital admin who approved', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_deployments', to='core.hospital')),
            ],
            options={
                'verbose_name': 'AI Deployment Log',
                'verbose_name_plural': 'AI Deployment Logs',
                'ordering': ['-enabled_at'],
                'indexes': [models.Index(fields=['hospital', 'enabled', '-enabled_at'], name='api_aideplo_hospita_7b8b37_idx')],
            },
        ),
    ]
