# Generated by Django 4.2.29 on 2026-04-21 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0029_hospital_archive_reason_hospital_archived_at_and_more'),
        ('api', '0006_add_ai_deployment_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_version', models.CharField(db_index=True, help_text='Model version identifier (e.g., 1.0.0-hybrid, 1.1.0-mimic-iv)', max_length=50, unique=True)),
                ('auc_roc', models.DecimalField(decimal_places=4, help_text='Area Under ROC Curve (0-1). Clinical min: 0.80', max_digits=4)),
                ('sensitivity', models.DecimalField(decimal_places=4, help_text='True Positive Rate (0-1). Clinical min: 0.75', max_digits=4)),
                ('specificity', models.DecimalField(decimal_places=4, help_text='True Negative Rate (0-1). Clinical min: 0.85', max_digits=4)),
                ('precision', models.DecimalField(blank=True, decimal_places=4, help_text='Precision (0-1)', max_digits=4, null=True)),
                ('f1_score', models.DecimalField(blank=True, decimal_places=4, help_text='F1 Score (0-1)', max_digits=4, null=True)),
                ('validation_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('dataset_size', models.IntegerField(help_text='Number of samples used in validation')),
                ('dataset_source', models.CharField(choices=[('mimic', 'MIMIC-IV (Medical Information Mart for Intensive Care)'), ('synthetic', 'Synthetic Ghana Data'), ('ghana', 'Real Ghana Health Service Data'), ('hybrid', 'Hybrid (Multiple Sources)'), ('kaggle', 'Kaggle Public Datasets'), ('uci', 'UCI Machine Learning Repository')], default='hybrid', help_text='Source of validation dataset', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes on model validation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'model_metrics',
                'ordering': ['-validation_date'],
                'indexes': [models.Index(fields=['model_version'], name='model_metri_model_v_a64b60_idx'), models.Index(fields=['-validation_date'], name='model_metri_validat_4dff1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIDeploymentApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_version', models.CharField(help_text='Model version being approved (e.g., 1.0.0-hybrid)', max_length=50)),
                ('approved_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When approval was revoked (if applicable)', null=True)),
                ('confidence_threshold', models.DecimalField(decimal_places=4, default='0.80', help_text='Minimum confidence threshold for this hospital (0.75-1.0)', max_digits=4)),
                ('enabled', models.BooleanField(default=True, help_text='Is this approval currently active?')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Config flags and approval context')),
                ('notes', models.TextField(blank=True, help_text='Approval notes (why approved, caveats, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Hospital admin who approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_approvals_given', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(help_text='Hospital approving this model', on_delete=django.db.models.deletion.CASCADE, related_name='ai_approvals', to='core.hospital')),
                ('revoked_by', models.ForeignKey(blank=True, help_text='Admin who revoked approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_approvals_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_deployment_approval',
                'ordering': ['-approved_at'],
                'indexes': [models.Index(fields=['hospital', 'enabled', '-approved_at'], name='ai_deployme_hospita_19ed15_idx'), models.Index(fields=['model_version', '-approved_at'], name='ai_deployme_model_v_782f57_idx')],
                'unique_together': {('hospital', 'model_version')},
            },
        ),
    ]
