# Generated by Django 4.2.29 on 2026-05-01 01:38

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_encounter_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_modelmetrics_aideploymentapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Human-readable rule name', max_length=200)),
                ('rule_type', models.CharField(choices=[('drug_interaction', 'Drug-Drug Interaction'), ('drug_allergy', 'Drug-Allergy Contraindication'), ('renal_dosing', 'Renal Dose Adjustment'), ('duplicate_therapy', 'Duplicate Therapy')], max_length=50)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Information')], max_length=20)),
                ('condition_json', models.JSONField(default=api.models._default_dict, help_text='Rule condition parameters')),
                ('action_json', models.JSONField(default=api.models._default_dict, help_text='Alert message and metadata')),
                ('active', models.BooleanField(default=True, help_text='Enable/disable this rule')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the rule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rule_type', '-severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CdsAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Information')], max_length=20)),
                ('message', models.TextField(help_text='Alert message to display to doctor')),
                ('context_data', models.JSONField(default=api.models._default_dict, help_text='Additional context for the alert (drug names, values, etc.)')),
                ('acknowledged', models.BooleanField(default=False, help_text='Has doctor acknowledged this alert?')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgment_notes', models.TextField(blank=True, help_text="Doctor's notes on acknowledgment")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_cds_alerts', to=settings.AUTH_USER_MODEL)),
                ('diagnosis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cds_alerts', to='records.diagnosis')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cds_alerts', to='records.encounter')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cds_alerts', to='records.prescription')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='api.clinicalrule')),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='clinicalrule',
            index=models.Index(fields=['rule_type', 'active'], name='api_clinica_rule_ty_fc61fd_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalrule',
            index=models.Index(fields=['severity'], name='api_clinica_severit_02f8b8_idx'),
        ),
        migrations.AddIndex(
            model_name='cdsalert',
            index=models.Index(fields=['encounter', '-created_at'], name='api_cdsaler_encount_9eb09a_idx'),
        ),
        migrations.AddIndex(
            model_name='cdsalert',
            index=models.Index(fields=['encounter', 'acknowledged'], name='api_cdsaler_encount_d5af51_idx'),
        ),
        migrations.AddIndex(
            model_name='cdsalert',
            index=models.Index(fields=['severity'], name='api_cdsaler_severit_3a06e5_idx'),
        ),
        migrations.AddIndex(
            model_name='cdsalert',
            index=models.Index(fields=['rule', 'severity'], name='api_cdsaler_rule_id_0fd00e_idx'),
        ),
    ]
