# Generated by Django 4.2.29 on 2026-05-01 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0019_encounter_updated_at_and_more'),
        ('core', '0030_alter_auditlog_chain_hash_alter_auditlog_signature_and_more'),
        ('api', '0008_clinicalrule_cdsalert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(help_text='Brand name or common name', max_length=200)),
                ('generic_name', models.CharField(blank=True, help_text='Generic/active ingredient', max_length=200)),
                ('batch_number', models.CharField(help_text='Manufacturer batch/lot number', max_length=50)),
                ('quantity', models.PositiveIntegerField(help_text='Current quantity in stock')),
                ('unit', models.CharField(choices=[('tablets', 'Tablets'), ('capsules', 'Capsules'), ('mL', 'Milliliters'), ('L', 'Liters'), ('grams', 'Grams'), ('mg', 'Milligrams'), ('vials', 'Vials'), ('ampoules', 'Ampoules'), ('units', 'Units'), ('patches', 'Patches'), ('tubes', 'Tubes'), ('inhalers', 'Inhalers'), ('sprays', 'Sprays'), ('drops', 'Drops')], help_text='Unit of measurement', max_length=20)),
                ('reorder_level', models.PositiveIntegerField(help_text='Minimum quantity before alert')),
                ('expiry_date', models.DateField(help_text='Expiration date of batch')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_stock', to='core.hospital')),
            ],
            options={
                'db_table': 'pharmacy_drug_stock',
            },
        ),
        migrations.CreateModel(
            name='Dispensation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_dispensed', models.PositiveIntegerField(help_text='Quantity given to patient')),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('batch_notes', models.TextField(blank=True, help_text='Pharmacy notes on dispensation')),
                ('dispensed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensed_medications', to=settings.AUTH_USER_MODEL)),
                ('drug_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispensations', to='api.drugstock')),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispensation', to='records.prescription')),
            ],
            options={
                'db_table': 'pharmacy_dispensation',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('received', 'Stock Received'), ('dispensed', 'Dispensed to Patient'), ('adjustment', 'Manual Adjustment'), ('expired', 'Expired/Destroyed'), ('damaged', 'Damaged'), ('transfer', 'Transfer to Another Hospital')], max_length=20)),
                ('quantity', models.IntegerField(help_text='Positive = added, negative = removed')),
                ('reason', models.TextField(blank=True, help_text='Reason for movement (adjustment reason, damaged qty, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispensation', models.ForeignKey(blank=True, help_text='Link to dispensation if movement_type=dispensed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.dispensation')),
                ('drug_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='api.drugstock')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pharmacy_stock_movement',
                'indexes': [models.Index(fields=['drug_stock', '-created_at'], name='pharmacy_st_drug_st_166d11_idx'), models.Index(fields=['movement_type', '-created_at'], name='pharmacy_st_movemen_19cca7_idx'), models.Index(fields=['performed_by', '-created_at'], name='pharmacy_st_perform_ebaf3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Already Expired')], max_length=20)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info')], default='warning', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_stock_alerts', to=settings.AUTH_USER_MODEL)),
                ('drug_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.drugstock')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_alerts', to='core.hospital')),
            ],
            options={
                'db_table': 'pharmacy_stock_alert',
                'indexes': [models.Index(fields=['hospital', 'status', '-created_at'], name='pharmacy_st_hospita_225384_idx'), models.Index(fields=['drug_stock', '-created_at'], name='pharmacy_st_drug_st_8981ba_idx'), models.Index(fields=['alert_type', 'status'], name='pharmacy_st_alert_t_3aa486_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='drugstock',
            index=models.Index(fields=['hospital', '-created_at'], name='pharmacy_dr_hospita_7f3a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='drugstock',
            index=models.Index(fields=['hospital', 'expiry_date'], name='pharmacy_dr_hospita_d811ae_idx'),
        ),
        migrations.AddIndex(
            model_name='drugstock',
            index=models.Index(fields=['drug_name', 'hospital'], name='pharmacy_dr_drug_na_103a14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='drugstock',
            unique_together={('hospital', 'drug_name', 'batch_number', 'expiry_date')},
        ),
        migrations.AddIndex(
            model_name='dispensation',
            index=models.Index(fields=['drug_stock', '-dispensed_at'], name='pharmacy_di_drug_st_8dacfc_idx'),
        ),
        migrations.AddIndex(
            model_name='dispensation',
            index=models.Index(fields=['dispensed_by', '-dispensed_at'], name='pharmacy_di_dispens_afd9ec_idx'),
        ),
    ]
