# Generated by Django 4.2.29 on 2026-05-02 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pharmacy_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='quantity_after',
            field=models.PositiveIntegerField(default=0, help_text='Stock quantity after movement'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='quantity_before',
            field=models.PositiveIntegerField(default=0, help_text='Stock quantity before movement'),
        ),
    ]
