# Generated by Django 4.2.29 on 2026-05-02 03:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_stockmovement_quantity_after_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseriskprediction',
            name='recommendations',
            field=models.JSONField(blank=True, default=api.models._default_list, help_text='Clinical recommendations for this disease'),
        ),
        migrations.AddIndex(
            model_name='diseaseriskprediction',
            index=models.Index(fields=['disease', '-risk_score'], name='disease_ris_disease_1f81e4_idx'),
        ),
        migrations.AddIndex(
            model_name='diseaseriskprediction',
            index=models.Index(fields=['risk_category'], name='disease_ris_risk_ca_959091_idx'),
        ),
    ]
