# Generated by Django 4.2.29 on 2026-05-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_squashed_0011_alter_diseaseriskprediction_recommendations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='alerts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='has_critical_alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='is_at_risk',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['is_at_risk', '-created_at'], name='ai_analysis_is_at_r_f10a6c_idx'),
        ),
        migrations.AddIndex(
            model_name='aianalysis',
            index=models.Index(fields=['has_critical_alerts'], name='ai_analysis_has_cri_371acc_idx'),
        ),
    ]
