# Generated by Django 4.2.29 on 2026-05-05 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_aianalysis_alerts_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_type', models.CharField(choices=[('risk_prediction', 'Risk Prediction'), ('triage', 'Triage'), ('diagnosis', 'Diagnosis'), ('similarity', 'Similarity Search')], max_length=50)),
                ('version_tag', models.CharField(help_text='e.g. v2.1.0-20260501', max_length=100)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('training_data_source', models.CharField(choices=[('synthetic', 'Synthetic Data'), ('anonymized_local', 'Anonymized Local Data'), ('anonymized_federated', 'Anonymized Federated Data')], default='synthetic', max_length=50)),
                ('training_sample_count', models.IntegerField(default=0)),
                ('evaluation_metrics', models.JSONField(default=dict)),
                ('comparison_vs_previous', models.JSONField(blank=True, default=dict, null=True)),
                ('is_production', models.BooleanField(default=False, help_text='Is this the currently active model in production?')),
                ('clinical_use_approved', models.BooleanField(default=False, help_text='Has this version been clinically validated?')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, help_text='Clinical validation summary', null=True)),
                ('joblib_path', models.CharField(help_text='Absolute path to the saved .joblib file', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_models', to=settings.AUTH_USER_MODEL)),
                ('trained_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_model_version',
                'ordering': ['-trained_at'],
                'indexes': [models.Index(fields=['model_type', 'is_production'], name='ai_model_ve_model_t_3d312f_idx'), models.Index(fields=['version_tag'], name='ai_model_ve_version_5da21e_idx')],
            },
        ),
    ]
