# Generated by Django 4.2.29 on 2026-05-22 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_prescription_prescribed_quantity_and_more'),
        ('api', '0013_modelversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensation',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensations', to='records.prescription'),
        ),
    ]
