# Generated by Django 4.2.29 on 2026-05-24 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_aianalysisjob_result_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='NHIADrug',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generic_name', models.CharField(help_text='Generic active ingredient name', max_length=255, unique=True)),
                ('nhia_code', models.CharField(help_text='NHIA Drug Code', max_length=50, unique=True)),
                ('approved_dosage_form', models.CharField(blank=True, help_text='e.g. tablet, syrup', max_length=150, null=True)),
                ('max_reimbursable_price', models.DecimalField(decimal_places=2, default=0.0, help_text='Max price covered by NHIS in GHS', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
