# Generated by Django 4.2.29 on 2026-06-03 11:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_nhiadrug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiagnosisSuggestion',
        ),
        migrations.DeleteModel(
            name='DiseaseRiskPrediction',
        ),
        migrations.DeleteModel(
            name='TriageAssessment',
        ),
        migrations.DeleteModel(
            name='PatientSimilarityMatch',
        ),
        migrations.DeleteModel(
            name='ReferralRecommendation',
        ),
        migrations.DeleteModel(
            name='AIAnalysisJob',
        ),
        migrations.DeleteModel(
            name='AIDeploymentApproval',
        ),
        migrations.DeleteModel(
            name='AIDeploymentLog',
        ),
        migrations.DeleteModel(
            name='ModelVersion',
        ),
        migrations.DeleteModel(
            name='AIAnalysis',
        ),
        migrations.DeleteModel(
            name='AIAnalysisCounter',
        ),
        migrations.DeleteModel(
            name='ModelMetrics',
        ),
        migrations.DeleteModel(
            name='NHIADrug',
        ),
        migrations.AlterField(
            model_name='cdsalert',
            name='context_data',
            field=models.JSONField(default=api.models._default_dict, help_text='Additional context for the alert'),
        ),
        migrations.AlterField(
            model_name='clinicalrule',
            name='action_json',
            field=models.JSONField(default=api.models._default_dict, help_text='Alert message and metadata'),
        ),
        migrations.AlterField(
            model_name='clinicalrule',
            name='condition_json',
            field=models.JSONField(default=api.models._default_dict, help_text='Rule condition parameters'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for movement'),
        ),
    ]
