# Generated by Django 4.2.29 on 2026-06-25 13:13

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_protect_cdsalert_encounter'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='drugstock',
            managers=[
                ('tenant_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='stockalert',
            managers=[
                ('tenant_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
