from django.urls import path
from api.views import (
    health_views,
    auth_views,
    patient_views,
    record_views,
    encounter_views,
    appointment_views,
    admin_views,
    alert_views,
    lab_views,
    admission_views,
    bed_views,
    dashboard_views,
    report_views,
    fhir_views,
    superadmin_views,
    audit_views,
    global_patient_views,
    referral_views,
    consent_views,
    break_glass_views,
    nurse_views,
    password_recovery_views,
    ai_views,
    task_views,
)

urlpatterns = [
    path("health", health_views.health),
    path("auth/login", auth_views.login),
    path("auth/mfa-verify", auth_views.mfa_verify),
    path("auth/activate", auth_views.activate),
    path("auth/activate-setup", auth_views.activate_setup),
    path("auth/forgot-password", auth_views.forgot_password),
    path("auth/reset-password", auth_views.reset_password),
    path("auth/login-temp-password", auth_views.login_with_temp_password),
    path("auth/change-password-on-login", auth_views.change_password_on_login),
    path("auth/refresh", auth_views.refresh),
    path("auth/logout", auth_views.logout),
    path("auth/me", auth_views.me),
    path("patients/search", patient_views.patient_search),
    path("patients/duplicate-check", patient_views.patient_duplicate_check),
    path("patients", patient_views.patient_create),
    path("patients/<uuid:pk>", patient_views.patient_detail),
    path("patients/<uuid:pk>/encounters", encounter_views.encounter_list),
    path("patients/<uuid:pk>/encounters/<uuid:encounter_id>", encounter_views.encounter_detail),
    path("patients/<uuid:pk>/encounters/<uuid:encounter_id>/close", encounter_views.close_encounter),
    path("patients/<uuid:pk>/records", patient_views.patient_records),
    path("patients/<uuid:pk>/diagnoses", patient_views.patient_diagnoses),
    path("patients/<uuid:pk>/prescriptions", patient_views.patient_prescriptions),
    path("patients/<uuid:pk>/labs", patient_views.patient_labs),
    path("patients/<uuid:pk>/vitals", patient_views.patient_vitals),
    path("patients/<uuid:pk>/allergies", patient_views.patient_allergies),
    path("patients/<uuid:pk>/export-pdf", patient_views.patient_export_pdf),
    path("records/diagnosis", record_views.create_diagnosis),
    path("icd10/search", record_views.icd10_autocomplete),
    path("records/icd10-autocomplete", record_views.icd10_autocomplete),
    path("records/prescription", record_views.create_prescription),
    path("records/drug-autocomplete", record_views.drug_autocomplete),
    path("records/prescription/<uuid:record_id>/dispense", record_views.prescription_dispense),
    path("records/prescription/<uuid:record_id>/dispense-by-nurse", record_views.prescription_dispense_by_nurse),
    path("records/lab-order", record_views.create_lab_order),
    path("records/vitals", record_views.create_vitals),
    path("records/vitals/batch", record_views.create_vitals_batch),
    path("records/allergy", record_views.create_allergy),
    path("records/nursing-note", record_views.create_nursing_note),
    path("records/radiology-order", record_views.create_radiology_order),
    path("records/radiology-order/<uuid:order_id>/attachment", record_views.radiology_order_attachment),
    path("records/<uuid:record_id>/amend", record_views.amend_record),
    
    # PHASE 6: Doctor Clinical Features
    path("doctor/favorites/prescriptions", record_views.doctor_favorite_prescriptions),
    path("doctor/prescriptions/<uuid:record_id>/refill", record_views.doctor_prescription_refill),
    path("doctor/records/<uuid:record_id>/amendment-history", record_views.doctor_amendment_history),
    path("admin/users", admin_views.user_list),
    path("admin/users/invite", admin_views.user_invite),
    path("admin/users/bulk-import", admin_views.user_bulk_import),
    path("admin/users/<uuid:pk>", admin_views.user_update),
    path("admin/users/<uuid:pk>/send-password-reset", admin_views.user_send_password_reset),
    path("admin/users/<uuid:pk>/reset-mfa", admin_views.user_reset_mfa),
    path("admin/users/<uuid:pk>/resend-invite", admin_views.user_resend_invite),
    path("admin/users/<uuid:pk>/role", admin_views.user_role_review),
    path("admin/rbac-review", admin_views.rbac_review_list),
    path("admin/audit-logs", admin_views.audit_logs),
    path("admin/staff-onboarding", admin_views.staff_onboarding_dashboard),
    path("alerts", alert_views.alert_list),
    path("alerts/<uuid:pk>/resolve", alert_views.alert_resolve),
    path("admin/wards/occupancy", admin_views.ward_occupancy),
    path("admin/wards/create", admin_views.ward_create),
    path("admin/wards", admin_views.ward_list),
    path("admin/wards/<uuid:ward_id>/beds/bulk", admin_views.ward_create_beds),
    path("admin/wards/<uuid:ward_id>", admin_views.ward_update),
    path("admin/departments", admin_views.department_list),
    path("admin/departments/create", admin_views.department_create),
    path("admin/lab-units", admin_views.lab_unit_list),
    path("admin/lab-units/create", admin_views.lab_unit_create),
    path("admin/lab-test-types", admin_views.lab_test_type_list),
    path("admin/lab-test-types/create", admin_views.lab_test_type_create),
    path("admin/doctors", admin_views.doctor_list),
    path("admin/duplicates", admin_views.duplicate_list),
    path("admin/duplicates/create", admin_views.duplicate_create),
    path("admin/duplicates/<uuid:duplicate_id>", admin_views.duplicate_detail),
    path("worklist/encounters", encounter_views.worklist_encounters),
    path("worklist", encounter_views.worklist_encounters),
    path("lab/orders", lab_views.lab_orders_list),
    path("lab/orders/<uuid:order_id>", lab_views.lab_order_detail),
    path("lab/attachments/upload", lab_views.lab_attachment_upload),
    path("lab/orders/<uuid:order_id>/result", lab_views.lab_order_result),
    path("admissions", admission_views.admissions_list),
    path("admissions/create", admission_views.admission_create),
    path("admissions/ward/<uuid:ward_id>", admission_views.admissions_by_ward),
    path("admissions/<uuid:admission_id>/discharge", admission_views.admission_discharge),
    path("admin/wards/<uuid:ward_id>/beds", bed_views.bed_list_by_ward),
    path("admin/beds", bed_views.bed_create),
    path("admin/beds/<uuid:bed_id>", bed_views.bed_update),
    path("dashboard", dashboard_views.dashboard_metrics),
    path("dashboard/metrics", dashboard_views.dashboard_metrics),
    path("dashboard/analytics", dashboard_views.dashboard_analytics),
    path("appointments", appointment_views.appointment_list),
    path("appointments/check-availability", appointment_views.appointment_check_availability),
    path("appointments/create", appointment_views.appointment_create),
    path("appointments/no-show-statistics", appointment_views.appointment_no_show_statistics),
    path("appointments/<uuid:pk>/delete", appointment_views.appointment_delete),
    path("appointments/<uuid:pk>/check-in", appointment_views.appointment_check_in),
    path("appointments/<uuid:pk>/reschedule", appointment_views.appointment_reschedule),
    path("appointments/<uuid:pk>/no-show", appointment_views.appointment_mark_no_show),
    path("appointments/<uuid:pk>/unmark-no-show", appointment_views.appointment_unmark_no_show),
    path("appointments/<uuid:pk>", appointment_views.appointment_update),
    path("reports/patients/export", report_views.export_patients_csv),
    path("reports/audit/export", report_views.export_audit_csv),
    path("audit/export", report_views.export_audit_csv),
    path("billing/invoices", report_views.invoice_list_create),
    path("billing/nhis-claim", report_views.nhis_claim_submit),
    path("fhir/Patient", fhir_views.fhir_patient_list),
    path("fhir/Patient/<uuid:pk>", fhir_views.fhir_patient_read),
    path("fhir/Encounter", fhir_views.fhir_encounter_list),
    path("fhir/Encounter/<uuid:pk>", fhir_views.fhir_encounter_read),
    path("fhir/Condition", fhir_views.fhir_condition_list),
    path("fhir/Condition/<uuid:pk>", fhir_views.fhir_condition_read),
    path("fhir/MedicationRequest", fhir_views.fhir_medication_request_list),
    path("fhir/MedicationRequest/<uuid:pk>", fhir_views.fhir_medication_request_read),
    path("fhir/Observation", fhir_views.fhir_observation_list),
    path("fhir/Observation/<uuid:pk>", fhir_views.fhir_observation_read),
    path("hl7/adt", fhir_views.hl7_adt_list),
    path("interop/fhir-push", fhir_views.fhir_push),
    path("superadmin/hospitals", superadmin_views.hospitals_list),
    path("superadmin/dashboard-bundle", superadmin_views.superadmin_dashboard_bundle),
    path("superadmin/hospital-onboarding-list", superadmin_views.hospital_onboarding_list),
    path("superadmin/audit-logs", superadmin_views.global_audit_logs),
    path("audit/global-logs", superadmin_views.global_audit_logs),
    path("audit/validate-chain", audit_views.validate_chain),
    path("superadmin/system-health", superadmin_views.system_health),
    path("superadmin/break-glass", superadmin_views.break_glass_list_global),
    path("superadmin/break-glass-list-global", superadmin_views.break_glass_list_global),
    path("superadmin/break-glass/<uuid:break_glass_id>/review", superadmin_views.break_glass_mark_reviewed),
    path("superadmin/break-glass/<uuid:break_glass_id>/flag-abuse", superadmin_views.break_glass_flag_abuse),
    path("superadmin/grant-hospital-access", superadmin_views.grant_hospital_access),
    path("superadmin/gmdc-unverified", superadmin_views.gmdc_unverified_doctors),
    path("superadmin/onboard-hospital", superadmin_views.onboard_hospital),
    path("superadmin/audit-chain-integrity", superadmin_views.audit_chain_integrity_status),
    path("superadmin/audit-chain-integrity/validate", superadmin_views.audit_chain_integrity_validate),
    path("superadmin/hospital-onboarding", superadmin_views.hospital_onboarding_status),
    path("superadmin/compliance-alerts", superadmin_views.compliance_alerts),
    path("superadmin/pending-hospital-admin-assignments", superadmin_views.pending_hospital_admin_assignments),
    path("superadmin/pending-admin-grants", superadmin_views.pending_admin_grants),
    # Interop: global patient registry, referrals, consent, break-glass
    path("global-patients/search", global_patient_views.global_patient_search),
    path("facility-patients/link", global_patient_views.facility_patient_link),
    path("facilities", global_patient_views.facilities_list),
    path("facilities/<uuid:pk>", global_patient_views.facility_update),
    path("cross-facility-records/<uuid:global_patient_id>", global_patient_views.cross_facility_records),
    path("referrals", referral_views.referral_create),
    path("referrals/incoming", referral_views.referral_incoming),
    path("referrals/<uuid:pk>", referral_views.referral_update),
    path("consents", consent_views.consent_grant),
    path("consents/list", consent_views.consent_list),
    path("consents/<uuid:pk>", consent_views.consent_revoke),
    path("break-glass", break_glass_views.break_glass_create),
    path("break-glass/list", break_glass_views.break_glass_list),
    
    # PHASE 6: Hospital Onboarding & Interop
    path("superadmin/onboarding-dashboard", superadmin_views.hospital_onboarding_dashboard),
    path("superadmin/hospitals/<uuid:hospital_id>/bulk-import-staff", superadmin_views.bulk_import_staff),
    path("superadmin/hospitals/<uuid:hospital_id>/connectivity", superadmin_views.hospital_interop_connectivity),
    path("superadmin/cross-facility-activity", superadmin_views.cross_facility_activity_log),
    
    # PHASE 6: Lab Technician Advanced Features
    path("lab/results/bulk-submit", lab_views.lab_results_bulk_submit),
    path("lab/analytics/trends", lab_views.lab_analytics_trends),
    
    # PHASE 6: Nurse Advanced Features
    path("nurse/dashboard", nurse_views.nurse_dashboard),
    path("nurse/worklist", nurse_views.nurse_worklist),
    path("nurse/shift/start", nurse_views.nurse_shift_start),
    path("nurse/shift/break-toggle", nurse_views.nurse_shift_break_toggle),
    path("nurse/shift/end", nurse_views.nurse_shift_end),
    path("nurse/shift/<uuid:shift_id>/handover", nurse_views.nurse_shift_handover),
    path("nurse/handover/<uuid:note_id>/acknowledge", nurse_views.nurse_handover_acknowledge),
    path("nurse/overdue-vitals", nurse_views.nurse_overdue_vitals),
    
    # PHASE 7: 3-Tier Password Recovery
    # Tier 2: Hospital Admin password reset
    path("admin/users/<uuid:user_id>/generate-reset-link", password_recovery_views.generate_reset_link),
    path("admin/users/<uuid:user_id>/generate-temp-password", password_recovery_views.generate_temp_password),
    path("admin/password-resets", password_recovery_views.get_password_reset_history),
    
    # Tier 3: Super Admin password reset
    path("superadmin/users/<uuid:user_id>/force-password-reset", password_recovery_views.force_password_reset),
    path("superadmin/users/<uuid:user_id>/force-password-reset-initiate", password_recovery_views.force_password_reset_initiate),
    path("superadmin/password-resets/suspicious", password_recovery_views.get_suspicious_resets),
    
    # PHASE 8: AI Intelligence Module
    path("ai/status", ai_views.ai_status),
    path("ai/analyze-patient/<uuid:patient_id>", ai_views.analyze_patient_comprehensive),
    path("ai/risk-prediction/<uuid:patient_id>", ai_views.predict_patient_risk),
    path("ai/clinical-decision-support/<uuid:patient_id>", ai_views.get_clinical_decision_support),
    path("ai/triage/<uuid:patient_id>", ai_views.triage_patient),
    path("ai/find-similar-patients/<uuid:patient_id>", ai_views.find_similar_patients),
    path("ai/referral-recommendation/<uuid:patient_id>", ai_views.recommend_referral_hospital),
    path("ai/analysis-history/<uuid:patient_id>", ai_views.get_analysis_history),
    
    # PHASE 9: Celery Task Status Endpoints
    path("tasks", task_views.task_list),
    path("tasks/<str:task_id>", task_views.task_status),
    path("tasks/<str:task_id>/result", task_views.task_result),
]
