from django.urls import path
from api.views import (
    health_views,
    auth_views,
    patient_views,
    record_views,
    encounter_views,
    appointment_views,
    admin_views,
    alert_views,
    lab_views,
    admission_views,
    bed_views,
    dashboard_views,
    report_views,
    billing_views,
    fhir_views,
    superadmin_views,
    audit_views,
    global_patient_views,
    referral_views,
    consent_views,
    break_glass_views,
    nurse_views,
    password_recovery_views,
    shift_views,
    batch_operations_views,
    mar_views,
    emergency_views,
    cds_views,
    step_up_views,
    pharmacy_views,
    pharmacy_stock_views,
    ai_views,
)

urlpatterns = [
    path("health", health_views.health, name="health"),
    path("auth/login", auth_views.login, name="auth_login"),
    path("auth/mfa-verify", auth_views.mfa_verify, name="auth_mfa_verify"),
    path("auth/activate", auth_views.activate, name="auth_activate"),
    path("auth/activate-setup", auth_views.activate_setup, name="auth_activate_setup"),
    path("auth/setup-totp", auth_views.setup_totp, name="auth_setup_totp"),
    path("auth/forgot-password", auth_views.forgot_password, name="auth_forgot_password"),
    path("auth/reset-password", auth_views.reset_password, name="auth_reset_password"),
    path("auth/login-temp-password", auth_views.login_with_temp_password, name="auth_login_temp_password"),
    path("auth/change-password-on-login", auth_views.change_password_on_login, name="auth_change_password_on_login"),
    path("auth/refresh", auth_views.refresh, name="auth_refresh"),
    path("auth/logout", auth_views.logout, name="auth_logout"),
    path("auth/me", auth_views.me, name="auth_me"),
    path("auth/step-up/request", step_up_views.step_up_request, name="auth_step_up_request"),
    path("auth/step-up/verify", step_up_views.step_up_verify, name="auth_step_up_verify"),
    # WebAuthn/Passkey authentication endpoints
    path("auth/passkey/register/begin", auth_views.passkey_register_begin, name="auth_passkey_register_begin"),
    path("auth/passkey/register/complete", auth_views.passkey_register_complete, name="auth_passkey_register_complete"),
    path("auth/passkey/check", auth_views.passkey_check, name="auth_passkey_check"),
    path("auth/passkey/auth/begin", auth_views.passkey_auth_begin, name="auth_passkey_auth_begin"),
    path("auth/passkey/auth/complete", auth_views.passkey_auth_complete, name="auth_passkey_auth_complete"),
    path("auth/passkeys", auth_views.list_passkeys, name="auth_passkeys_list"),
    path("auth/passkeys/<uuid:pk>", auth_views.delete_passkey, name="auth_passkey_detail"),
    path("auth/passkeys/<uuid:pk>/rename", auth_views.rename_passkey, name="auth_passkey_rename"),
    path("admin/users/<uuid:user_id>/passkeys", auth_views.admin_list_user_passkeys, name="admin_user_passkeys"),
    path("admin/users/<uuid:user_id>/passkeys/reset", auth_views.admin_reset_user_passkeys, name="admin_user_passkeys_reset"),
    # PHASE 3: HttpOnly Cookie-Based Authentication
    path("auth/refresh-cookie", auth_views.refresh_with_cookie, name="auth_refresh_cookie"),
    path("auth/logout-cookie", auth_views.logout_with_cookie, name="auth_logout_cookie"),
    path("auth/csrf-token", auth_views.get_csrf_token_endpoint, name="auth_csrf_token"),
    path("patients/search/", patient_views.patient_search, name="patient_search"),
    path("patients/duplicate-check", patient_views.patient_duplicate_check, name="patient_duplicate_check"),
    path("patients", patient_views.patient_create, name="patient_create"),
    path("patients/<uuid:pk>/", patient_views.patient_detail, name="patient_detail"),
    path("patients/<uuid:pk>/encounters", encounter_views.encounter_list, name="encounter_list"),
    path("patients/<uuid:pk>/encounters/<uuid:encounter_id>", encounter_views.encounter_detail, name="encounter_detail"),
    path("patients/<uuid:pk>/encounters/<uuid:encounter_id>/close", encounter_views.close_encounter, name="encounter_close"),
    path("patients/<uuid:pk>/encounters/<uuid:encounter_id>/draft", encounter_views.encounter_draft_handler, name="encounter_draft"),
    path(
        "patients/<uuid:pk>/draft",
        encounter_views.encounter_draft_handler,
        name="patient_draft",
    ),  # Patient-scoped draft (no encounter yet)
    # PHASE 7.1: Encounter Templates
    path("encounter-templates", encounter_views.encounter_template_list, name="encounter_template_list"),
    path("encounter-templates/<uuid:template_id>", encounter_views.encounter_template_detail, name="encounter_template_detail"),
    path("patients/<uuid:patient_pk>/encounters/<uuid:encounter_id>/apply-template/<uuid:template_id>",
         encounter_views.apply_encounter_template, name="encounter_apply_template"),
    path("patients/<uuid:pk>/records/", patient_views.patient_records, name="patient_records"),
    path("patients/<uuid:pk>/diagnoses", patient_views.patient_diagnoses, name="patient_diagnoses"),
    path("patients/<uuid:pk>/prescriptions", patient_views.patient_prescriptions, name="patient_prescriptions"),
    path("patients/<uuid:pk>/labs", patient_views.patient_labs, name="patient_labs"),
    path("patients/<uuid:pk>/vitals", patient_views.patient_vitals, name="patient_vitals"),
    path("patients/<uuid:pk>/obs-chart", record_views.patient_observation_chart, name="patient_obs_chart"),
    path("patients/<uuid:pk>/allergies", patient_views.patient_allergies, name="patient_allergies"),
    path("patients/<uuid:pk>/chronic-programs", patient_views.patient_chronic_programs, name="patient_chronic_programs"),
    path("patients/<uuid:pk>/family-links", patient_views.patient_family_links, name="patient_family_links"),
    path("patients/<uuid:pk>/export-pdf", patient_views.patient_export_pdf, name="patient_export_pdf"),
    path("records/diagnosis/", record_views.create_diagnosis, name="record_diagnosis_create"),
    path("icd10/search", record_views.icd10_autocomplete, name="icd10_search"),
    path("records/icd10-autocomplete", record_views.icd10_autocomplete, name="record_icd10_autocomplete"),
    path("records/prescription/", record_views.create_prescription, name="record_prescription_create"),
    path("records/drug-autocomplete", record_views.drug_autocomplete, name="record_drug_autocomplete"),
    path("records/prescription/<uuid:record_id>/dispense", record_views.prescription_dispense, name="record_prescription_dispense"),
    path("records/prescription/<uuid:record_id>/dispense-by-nurse", record_views.prescription_dispense_by_nurse, name="record_prescription_dispense_nurse"),
    path("records/prescriptions/pending-by-ward", record_views.prescriptions_pending_by_ward, name="record_prescriptions_pending_by_ward"),
    path("records/lab-order", record_views.create_lab_order, name="record_lab_order_create"),
    path("records/vitals", record_views.create_vitals, name="record_vitals_create"),
    path("records/vitals/batch", record_views.create_vitals_batch, name="record_vitals_batch"),
    path("records/allergy", record_views.create_allergy, name="record_allergy_create"),
    path("records/nursing-note", record_views.create_nursing_note, name="record_nursing_note_create"),
    path("records/immunisation", record_views.create_immunisation, name="record_immunisation_create"),
    path("records/procedure-note", record_views.create_procedure_note, name="record_procedure_note_create"),
    path("records/notifiable-disease", record_views.create_notifiable_disease, name="record_notifiable_disease_create"),
    path("records/radiology-order", record_views.create_radiology_order, name="record_radiology_order_create"),
    path("records/radiology-order/<uuid:order_id>/attachment", record_views.radiology_order_attachment, name="record_radiology_order_attachment"),
    path("records/<uuid:record_id>/amend", record_views.amend_record, name="record_amend"),

    # PHASE 7.2: Incident Reporting
    path("incidents", record_views.create_incident, name="incident_create"),
    path("incidents/list", record_views.list_incidents, name="incident_list"),

    # PHASE 6: Doctor Clinical Features
    path("doctor/favorites/prescriptions", record_views.doctor_favorite_prescriptions, name="doctor_favorite_prescriptions"),
    path("doctor/prescriptions/<uuid:record_id>/refill", record_views.doctor_prescription_refill, name="doctor_prescription_refill"),
    path("doctor/records/<uuid:record_id>/amendment-history", record_views.doctor_amendment_history, name="doctor_amendment_history"),
    path("admin/users", admin_views.user_list, name="admin_user_list"),
    path("admin/users/invite", admin_views.user_invite, name="admin_user_invite"),
    path("admin/users/bulk-import", admin_views.user_bulk_import, name="admin_user_bulk_import"),
    path("admin/users/<uuid:pk>", admin_views.user_update, name="admin_user_detail"),
    path("admin/users/<uuid:pk>/send-password-reset", admin_views.user_send_password_reset, name="admin_user_send_password_reset"),
    path("admin/users/<uuid:pk>/reset-mfa", admin_views.user_reset_mfa, name="admin_user_reset_mfa"),
    path("admin/users/<uuid:pk>/resend-invite", admin_views.user_resend_invite, name="admin_user_resend_invite"),
    path("admin/users/<uuid:pk>/role", admin_views.user_role_review, name="admin_user_role"),
    path("admin/rbac-review", admin_views.rbac_review_list, name="admin_rbac_review"),
    path("admin/audit-logs", admin_views.audit_logs, name="admin_audit_logs"),
    path("admin/equipment", admin_views.hospital_equipment, name="admin_equipment"),
    path("admin/staff-onboarding", admin_views.staff_onboarding_dashboard, name="admin_staff_onboarding"),
    path("admin/analytics/staff-performance", admin_views.staff_performance_analytics, name="admin_staff_performance"),
    # PHASE 7.6: Super Admin Analytics
    path("superadmin/analytics/network-overview", admin_views.network_overview, name="superadmin_network_overview"),
    path("superadmin/analytics/disease-burden", admin_views.disease_burden, name="superadmin_disease_burden"),
    path("superadmin/analytics/referral-network", admin_views.referral_network, name="superadmin_referral_network"),
    path("superadmin/gpid-registry/duplicates", admin_views.gpid_duplicates, name="superadmin_gpid_duplicates"),
    path("alerts", alert_views.alert_list, name="alert_list"),
    path("alerts/active-by-ward", alert_views.alerts_active_by_ward, name="alert_active_by_ward"),
    path("alerts/<uuid:pk>/resolve", alert_views.alert_resolve, name="alert_resolve"),
    path("admin/wards/occupancy", admin_views.ward_occupancy, name="admin_ward_occupancy"),
    path("admin/wards/create", admin_views.ward_create, name="admin_ward_create"),
    path("admin/wards", admin_views.ward_list, name="admin_ward_list"),
    path("admin/wards/<uuid:ward_id>/beds/bulk", admin_views.ward_create_beds, name="admin_ward_beds_bulk"),
    path("admin/wards/<uuid:ward_id>", admin_views.ward_update, name="admin_ward_detail"),
    path("admin/departments", admin_views.department_list, name="admin_department_list"),
    path("admin/departments/create", admin_views.department_create, name="admin_department_create"),
    path("admin/lab-units", admin_views.lab_unit_list, name="admin_lab_unit_list"),
    path("admin/lab-units/create", admin_views.lab_unit_create, name="admin_lab_unit_create"),
    path("admin/lab-test-types", admin_views.lab_test_type_list, name="admin_lab_test_type_list"),
    path("admin/lab-test-types/create", admin_views.lab_test_type_create, name="admin_lab_test_type_create"),
    path("admin/doctors", admin_views.doctor_list, name="admin_doctor_list"),
    path("admin/duplicates", admin_views.duplicate_list, name="admin_duplicate_list"),
    path("admin/duplicates/create", admin_views.duplicate_submit, name="admin_duplicate_create"),
    path("admin/duplicates/<uuid:duplicate_id>", admin_views.duplicate_detail, name="admin_duplicate_detail"),
    path("worklist/encounters", encounter_views.worklist_encounters, name="worklist_encounters"),
    path("worklist", encounter_views.worklist_encounters, name="worklist"),
    path("lab/orders", lab_views.lab_orders_list, name="lab_order_list"),
    path("lab/orders/<uuid:order_id>", lab_views.lab_order_detail, name="lab_order_detail"),
    path("lab/attachments/upload", lab_views.lab_attachment_upload, name="lab_attachment_upload"),
    path("lab/orders/<uuid:order_id>/result", lab_views.lab_order_result, name="lab_order_result"),
    path("admissions", admission_views.admissions_list, name="admission_list"),
    path("admissions/create", admission_views.admission_create, name="admission_create"),
    path("admissions/ward/<uuid:ward_id>", admission_views.admissions_by_ward, name="admissions_by_ward"),
    path("admissions/ward/<uuid:ward_id>/dashboard", admission_views.admissions_by_ward_dashboard, name="admissions_by_ward_dashboard"),
    path("admissions/<uuid:admission_id>/discharge", admission_views.admission_discharge, name="admission_discharge"),
    path("admin/wards/<uuid:ward_id>/beds", bed_views.bed_list_by_ward, name="admin_ward_beds"),
    path("admin/beds", bed_views.bed_create, name="admin_bed_create"),
    path("admin/beds/<uuid:bed_id>", bed_views.bed_update, name="admin_bed_detail"),
    path("dashboard", dashboard_views.dashboard_metrics, name="dashboard"),
    path("dashboard/metrics", dashboard_views.dashboard_metrics, name="dashboard_metrics"),
    path("dashboard/analytics", dashboard_views.dashboard_analytics, name="dashboard_analytics"),
    path("appointments", appointment_views.appointment_list, name="appointment_list"),
    path("appointments/check-availability", appointment_views.appointment_check_availability, name="appointment_check_availability"),
    path("appointments/create", appointment_views.appointment_create, name="appointment_create"),
    path("appointments/bulk-import", appointment_views.appointment_bulk_import, name="appointment_bulk_import"),
    path("appointments/no-show-statistics", appointment_views.appointment_no_show_statistics, name="appointment_no_show_statistics"),
    path("appointments/walk-in", appointment_views.create_walk_in, name="appointment_walk_in"),
    path("appointments/walk-in-queue", appointment_views.walk_in_queue, name="appointment_walk_in_queue"),
    path("doctors/<uuid:doctor_id>/availability", appointment_views.doctor_availability, name="doctor_availability"),
    path("departments/<uuid:department_id>/doctors", appointment_views.department_doctors, name="department_doctors"),
    path("appointments/<uuid:pk>/delete", appointment_views.appointment_delete, name="appointment_delete"),
    path("appointments/<uuid:pk>/check-in", appointment_views.appointment_check_in, name="appointment_check_in"),
    path("appointments/<uuid:pk>/reschedule", appointment_views.appointment_reschedule, name="appointment_reschedule"),
    path("appointments/<uuid:pk>/no-show", appointment_views.appointment_mark_no_show, name="appointment_no_show"),
    path("appointments/<uuid:pk>/unmark-no-show", appointment_views.appointment_unmark_no_show, name="appointment_unmark_no_show"),
    path("appointments/<uuid:pk>", appointment_views.appointment_update, name="appointment_detail"),
    path("reports/patients/export", report_views.export_patients_csv, name="report_patients_export"),
    path("reports/audit/export", report_views.export_audit_csv, name="report_audit_export"),
    path("audit/export", report_views.export_audit_csv, name="audit_export"),
    path("billing/invoices", report_views.invoice_list_create, name="billing_invoice_list"),
    # billing/nhis-claim (old stub) removed — use billing/invoices/<id>/submit-nhis instead
    path("billing/nhis/eligibility", billing_views.check_nhis_eligibility, name="billing_nhis_eligibility"),
    path("billing/dashboard", billing_views.billing_dashboard, name="billing_dashboard"),
    path("billing/invoices/new", billing_views.create_invoice, name="billing_invoice_create"),
    path("billing/invoices/<uuid:invoice_id>/pay", billing_views.record_payment, name="billing_invoice_pay"),
    path("billing/invoices/<uuid:invoice_id>/submit-nhis", billing_views.submit_nhis_claim, name="billing_invoice_submit_nhis"),
    path("billing/invoices/<uuid:invoice_id>/nhis-status", billing_views.get_nhis_claim_status, name="billing_invoice_nhis_status"),
    path("patients/<uuid:patient_id>/billing-history", billing_views.patient_billing_history, name="patient_billing_history"),
    path("health/smtp-test", health_views.test_smtp, name="health_smtp_test"),
    path("fhir/metadata", fhir_views.fhir_capability_statement, name="fhir_metadata"),
    path("fhir/Patient", fhir_views.fhir_patient_list, name="fhir_patient_list"),
    path("fhir/Patient/<uuid:pk>/$everything", fhir_views.fhir_patient_everything, name="fhir_patient_everything"),
    path("fhir/Patient/<uuid:pk>", fhir_views.fhir_patient_read, name="fhir_patient_detail"),
    path("fhir/Encounter", fhir_views.fhir_encounter_list, name="fhir_encounter_list"),
    path("fhir/Encounter/<uuid:pk>", fhir_views.fhir_encounter_read, name="fhir_encounter_detail"),
    path("fhir/Condition", fhir_views.fhir_condition_list, name="fhir_condition_list"),
    path("fhir/Condition/<uuid:pk>", fhir_views.fhir_condition_read, name="fhir_condition_detail"),
    # FHIR write: POST /fhir/MedicationRequest and /fhir/Observation (no trailing slash,
    # matching the FHIR REST spec; both routes handled by method-dispatching views).
    path("fhir/MedicationRequest", fhir_views.fhir_medication_request_list_create, name="fhir_medication_request_list"),
    path("fhir/MedicationRequest/<uuid:pk>", fhir_views.fhir_medication_request_read, name="fhir_medication_request_detail"),
    path("fhir/Observation", fhir_views.fhir_observation_list_create, name="fhir_observation_list"),
    path("fhir/Observation/<uuid:pk>", fhir_views.fhir_observation_read, name="fhir_observation_detail"),
    path("fhir/DiagnosticReport/<uuid:pk>", fhir_views.fhir_diagnostic_report_read, name="fhir_diagnostic_report_detail"),
    path("hl7/adt", fhir_views.hl7_adt_list, name="hl7_adt"),
    path("interop/fhir-push", fhir_views.fhir_push, name="interop_fhir_push"),
    path("superadmin/hospitals", superadmin_views.hospitals_list, name="superadmin_hospital_list"),
    path("superadmin/dashboard-bundle", superadmin_views.superadmin_dashboard_bundle, name="superadmin_dashboard_bundle"),
    path("superadmin/hospital-onboarding-list", superadmin_views.hospital_onboarding_list, name="superadmin_hospital_onboarding_list"),
    path("superadmin/audit-logs", superadmin_views.global_audit_logs, name="superadmin_audit_logs"),
    path("audit/global-logs", superadmin_views.global_audit_logs, name="audit_global_logs"),
    path("audit/validate-chain", audit_views.validate_chain, name="audit_validate_chain"),
    path("superadmin/system-health", superadmin_views.system_health, name="superadmin_system_health"),
    path("superadmin/break-glass", superadmin_views.break_glass_list_global, name="superadmin_break_glass_list"),
    path("superadmin/break-glass-list-global", superadmin_views.break_glass_list_global, name="superadmin_break_glass_list_global"),
    path("superadmin/break-glass/<uuid:break_glass_id>/review", superadmin_views.break_glass_mark_reviewed, name="superadmin_break_glass_review"),
    path("superadmin/break-glass/<uuid:break_glass_id>/flag-abuse", superadmin_views.break_glass_flag_abuse, name="superadmin_break_glass_flag_abuse"),
    path("superadmin/grant-hospital-access", superadmin_views.grant_hospital_access, name="superadmin_grant_hospital_access"),
    path("superadmin/gmdc-unverified", superadmin_views.gmdc_unverified_doctors, name="superadmin_gmdc_unverified"),
    path("superadmin/onboard-hospital", superadmin_views.onboard_hospital, name="superadmin_onboard_hospital"),
    path("superadmin/audit-chain-integrity", superadmin_views.audit_chain_integrity_status, name="superadmin_audit_chain_integrity"),
    path("superadmin/audit-chain-integrity/validate", superadmin_views.audit_chain_integrity_validate, name="superadmin_audit_chain_integrity_validate"),
    path("superadmin/hospital-onboarding", superadmin_views.hospital_onboarding_status, name="superadmin_hospital_onboarding"),
    path("superadmin/compliance-alerts", superadmin_views.compliance_alerts, name="superadmin_compliance_alerts"),
    path("superadmin/security/alerts", admin_views.security_alerts, name="superadmin_security_alerts"),
    path("superadmin/pending-hospital-admin-assignments", superadmin_views.pending_hospital_admin_assignments, name="superadmin_pending_admin_assignments"),
    path("superadmin/pending-admin-grants", superadmin_views.pending_admin_grants, name="superadmin_pending_admin_grants"),
    # Interop: global patient registry, referrals, consent, break-glass
    path("global-patients/search/", global_patient_views.global_patient_search, name="global_patient_search"),
    path("global-patients/accessible/", global_patient_views.accessible_patients, name="global_patient_accessible"),
    path("facility-patients/link/", global_patient_views.facility_patient_link, name="facility_patient_link"),
    path("facilities", global_patient_views.facilities_list, name="facility_list"),
    path("facilities/<uuid:pk>", global_patient_views.facility_update, name="facility_detail"),
    path("cross-facility-records/<uuid:global_patient_id>/", global_patient_views.cross_facility_records, name="cross_facility_records"),
    path("referrals", referral_views.referral_create, name="referral_create"),
    path("referrals/incoming", referral_views.referral_incoming, name="referral_incoming"),
    path("referrals/outgoing", referral_views.referral_outgoing, name="referral_outgoing"),
    path("referrals/mine", referral_views.my_referrals, name="referral_mine"),
    path("referrals/<uuid:pk>", referral_views.referral_update, name="referral_detail"),
    path("referrals/<uuid:pk>/accept", referral_views.accept_referral, name="referral_accept"),
    path("referrals/<uuid:pk>/complete", referral_views.complete_referral, name="referral_complete"),
    path("consents", consent_views.consent_grant, name="consent_create"),
    path("consents/list", consent_views.consent_list, name="consent_list"),
    path("consents/<uuid:pk>", consent_views.consent_revoke, name="consent_revoke"),
    path("break-glass", break_glass_views.break_glass_create, name="break_glass_create"),
    path("break-glass/list", break_glass_views.break_glass_list, name="break_glass_list"),

    # PHASE 6: Hospital Onboarding & Interop
    path("superadmin/onboarding-dashboard", superadmin_views.hospital_onboarding_dashboard, name="superadmin_onboarding_dashboard"),
    path("superadmin/hospitals/<uuid:hospital_id>/bulk-import-staff", superadmin_views.bulk_import_staff, name="superadmin_bulk_import_staff"),
    path("superadmin/hospitals/<uuid:hospital_id>/connectivity", superadmin_views.hospital_interop_connectivity, name="superadmin_hospital_connectivity"),
    path("superadmin/cross-facility-activity", superadmin_views.cross_facility_activity_log, name="superadmin_cross_facility_activity"),

    # PHASE 6: Lab Technician Advanced Features
    path("lab/results/bulk-submit", lab_views.lab_results_bulk_submit, name="lab_results_bulk_submit"),
    path("lab/results", lab_views.lab_results_list, name="lab_result_list"),
    path("lab/analytics/trends", lab_views.lab_analytics_trends, name="lab_analytics_trends"),

    # PHASE 6: Nurse Advanced Features
    path("nurse/dashboard", nurse_views.nurse_dashboard, name="nurse_dashboard"),
    path("nurse/worklist", nurse_views.nurse_worklist, name="nurse_worklist"),
    path("nurse/shift/start", nurse_views.nurse_shift_start, name="nurse_shift_start"),
    path("nurse/shift/break-toggle", nurse_views.nurse_shift_break_toggle, name="nurse_shift_break_toggle"),
    path("nurse/shift/end", nurse_views.nurse_shift_end, name="nurse_shift_end"),
    path("nurse/shift/<uuid:shift_id>/handover", nurse_views.nurse_shift_handover, name="nurse_shift_handover"),
    path("nurse/shift-handover/<uuid:handover_id>/acknowledge", nurse_views.nurse_shift_handover_acknowledge, name="nurse_shift_handover_acknowledge"),
    path("nurse/handover/<uuid:note_id>/acknowledge", nurse_views.nurse_handover_acknowledge, name="nurse_handover_acknowledge"),
    path("nurse/overdue-vitals", nurse_views.nurse_overdue_vitals, name="nurse_overdue_vitals"),

    # PHASE 7.2: Nurse Medication Schedule
    path("ward/medication-schedule", record_views.medication_schedule, name="ward_medication_schedule"),
    path("prescriptions/<uuid:prescription_id>/administer", record_views.record_medication_administration, name="prescription_administer"),

    # PHASE 3: Shift Management (generic for all clinical roles)
    path("shifts/start", shift_views.shift_start, name="shift_start"),
    path("shifts/<uuid:shift_id>/end", shift_views.shift_end, name="shift_end"),
    path("shifts/current", shift_views.shift_current, name="shift_current"),
    path("shifts/<uuid:shift_id>/break/start", shift_views.shift_break_start, name="shift_break_start"),
    path("shifts/<uuid:shift_id>/break/end", shift_views.shift_break_end, name="shift_break_end"),
    path("shifts/<uuid:shift_id>/handover", shift_views.shift_handover_submit, name="shift_handover_submit"),
    path("shifts/handover-history", shift_views.shift_handover_history, name="shift_handover_history"),
    path("shifts/<uuid:shift_id>/statistics", shift_views.shift_statistics, name="shift_statistics"),
    path("shifts/roster", shift_views.shift_roster_list, name="shift_roster_list"),
    path("shifts/roster/create", shift_views.shift_schedule_create, name="shift_schedule_create"),
    path("shifts/schedule/<uuid:schedule_id>", shift_views.shift_schedule_update, name="shift_schedule_detail"),
    path("shifts/schedule/<uuid:schedule_id>/delete", shift_views.shift_schedule_delete, name="shift_schedule_delete"),
    path("shifts/check-conflict", shift_views.shift_check_conflict, name="shift_check_conflict"),
    path("shifts/overtime-report", shift_views.shift_overtime_report, name="shift_overtime_report"),

    # PHASE 4: Batch Operations
    path("batch-import", batch_operations_views.batch_import_create, name="batch_import_create"),
    path("batch-operations/summary", batch_operations_views.batch_operations_summary, name="batch_operations_summary"),
    path("batch-import/<uuid:job_id>", batch_operations_views.batch_import_detail, name="batch_import_detail"),
    path("batch-import/<uuid:job_id>/items", batch_operations_views.batch_import_items_list, name="batch_import_items"),
    path("batch-import/<uuid:job_id>/export", batch_operations_views.batch_import_export, name="batch_import_export"),
    path("bulk-invitations", batch_operations_views.bulk_invitation_create, name="bulk_invitation_create"),
    path("bulk-invitations/<uuid:campaign_id>", batch_operations_views.bulk_invitation_detail, name="bulk_invitation_detail"),
    path("bulk-invitations/expiration-check", batch_operations_views.bulk_invitation_expiration_check, name="bulk_invitation_expiration_check"),
    path("bulk-invitations/send-reminders", batch_operations_views.bulk_invitation_send_reminders, name="bulk_invitation_send_reminders"),
    path("bulk-invitations/reminder-schedule", batch_operations_views.bulk_invitation_reminder_schedule, name="bulk_invitation_reminder_schedule"),

    # PHASE 7: 3-Tier Password Recovery
    # Tier 2: Hospital Admin password reset
    path("admin/users/<uuid:user_id>/generate-reset-link", password_recovery_views.generate_reset_link, name="admin_user_generate_reset_link"),
    path("admin/users/<uuid:user_id>/generate-temp-password", password_recovery_views.generate_temp_password, name="admin_user_generate_temp_password"),
    path("admin/password-resets", password_recovery_views.get_password_reset_history, name="admin_password_resets"),

    # Tier 3: Super Admin password reset
    path("superadmin/users/<uuid:user_id>/force-password-reset", password_recovery_views.force_password_reset, name="superadmin_force_password_reset"),
    path("superadmin/users/<uuid:user_id>/force-password-reset-initiate",
         password_recovery_views.force_password_reset_initiate, name="superadmin_force_password_reset_initiate"),
    path("superadmin/password-resets/suspicious", password_recovery_views.get_suspicious_resets, name="superadmin_suspicious_resets"),

    # PHASE 5.1: Push Notifications Backend
    path("admin/bed-management", admin_views.bed_management_dashboard, name="admin_bed_management"),
    path("admissions/<uuid:admission_id>/transfer", admin_views.patient_transfer, name="admission_transfer"),

    # EMERGENCY DEPARTMENT: Triage & Queue Management
    path("emergency/triage/<uuid:appointment_id>", emergency_views.assign_triage_color, name="emergency_triage"),
    path("emergency/queue", emergency_views.ed_queue_realtime, name="emergency_queue"),
    path("emergency/room/<uuid:appointment_id>", emergency_views.assign_ed_room, name="emergency_room"),

    # AI: Discharge summary generation
    path("encounters/<uuid:encounter_id>/generate-discharge-summary", ai_views.generate_encounter_discharge_summary, name="encounter_generate_discharge_summary"),

    # PHASE 10: Clinical Decision Support (CDS) Rules Engine
    path("encounters/<uuid:encounter_id>/cds-alerts", cds_views.encounter_cds_alerts, name="encounter_cds_alerts"),
    path("cds-alerts/<uuid:alert_id>", cds_views.cds_alert_detail, name="cds_alert_detail"),
    path("cds-alerts/<uuid:alert_id>/acknowledge", cds_views.acknowledge_cds_alert, name="cds_alert_acknowledge"),
    # Pharmacy dispensing and worklist endpoints
    path("pharmacy/worklist", pharmacy_views.pharmacy_worklist, name="pharmacy_worklist"),
    path("pharmacy/dispense/<uuid:prescription_id>", pharmacy_views.dispense_medication, name="pharmacy_dispense"),
    path("pharmacy/statistics", pharmacy_views.pharmacy_statistics, name="pharmacy_statistics"),
    # Pharmacy stock management and reporting
    path("pharmacy/stock", pharmacy_stock_views.stock_list_create, name="pharmacy_stock_list"),
    path("pharmacy/stock/<uuid:stock_id>", pharmacy_stock_views.stock_detail, name="pharmacy_stock_detail"),
    path("pharmacy/stock/<uuid:stock_id>/adjust", pharmacy_stock_views.adjust_stock, name="pharmacy_stock_adjust"),
    path("pharmacy/dispensations", pharmacy_stock_views.dispensation_list, name="pharmacy_dispensation_list"),
    path("pharmacy/reports/low-stock", pharmacy_stock_views.low_stock_report, name="pharmacy_low_stock_report"),
    path("pharmacy/reports/expiring", pharmacy_stock_views.expiring_stock_report, name="pharmacy_expiring_stock_report"),
    path("pharmacy/tasks/check-expiry", pharmacy_stock_views.check_expiry_manual_trigger, name="pharmacy_check_expiry"),
    path("pharmacy/prescriptions/<uuid:prescription_id>/dispense-confirm", pharmacy_stock_views.dispense_confirm, name="pharmacy_dispense_confirm"),

    # MAR: Medication Administration Record
    path("mar/ward/<uuid:ward_id>/due", mar_views.ward_medications_due, name="mar_ward_due"),
    path("mar/administer/<uuid:schedule_id>", mar_views.administer_medication, name="mar_administer"),
    path("mar/hold/<uuid:schedule_id>", mar_views.hold_medication, name="mar_hold"),
    path("mar/patient/<uuid:patient_id>/schedule", mar_views.patient_medication_schedule, name="mar_patient_schedule"),
]
