# Generated by Django 4.2.29 on 2026-05-02 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    replaces = [('records', '0001_blueprint_alerts_encounters'), ('records', '0002_encounter'), ('records', '0003_workflow_encounter_lab'), ('records', '0004_rename_records_enc_dept_st_idx_records_enc_assigne_51c098_idx_and_more'), ('records', '0005_clinical_docs_visit_status'), ('records', '0006_radiology_order'), ('records', '0007_nurseshift_shifthandover_and_more'), ('records', '0008_nursingnote_handover_signatures'), ('records', '0009_laborder_state_machine_fields'), ('records', '0010_encounter_draft'), ('records', '0011_sbar_handover_signatures'), ('records', '0012_add_encounter_template'), ('records', '0013_add_version_field'), ('records', '0014_incident_medicationadministration_and_more'), ('records', '0015_pharmacy_dispensing'), ('records', '0016_medication_schedule'), ('records', '0017_rename_records_enc_patient_fa1f48_idx_encounter_patient_0dba2d_idx_and_more'), ('records', '0018_remove_encounter_records_enc_patient_fa1f48_idx_and_more'), ('records', '0019_encounter_updated_at_and_more')]

    initial = True

    dependencies = [
        ('core', '0021_add_password_reset_attempt_model'),
        ('core', '0003_blueprint_alerts_encounters'),
        ('core', '0007_invoice_billing'),
        ('core', '0023_add_version_field'),
        ('core', '0005_workflow_department_lab_unit'),
        ('patients', '0005_invoice_billing'),
        ('core', '0025_announcement'),
        ('core', '0022_add_hospital_ai_enabled'),
        ('core', '0019_user_last_role_reviewed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0010_add_walkin_fields'),
        ('patients', '0008_encrypt_phi_fields'),
        ('core', '0001_initial'),
        ('patients', '0001_blueprint_alerts_encounters'),
        ('core', '0010_superadminhospitalaccess'),
        ('patients', '0009_add_version_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=200)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('diagnosis', 'Diagnosis'), ('prescription', 'Prescription'), ('lab_result', 'Lab Result'), ('vital_signs', 'Vital Signs'), ('nursing_note', 'Nursing Note'), ('allergy', 'Allergy')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record_version', models.IntegerField(default=0)),
                ('is_amended', models.BooleanField(default=False)),
                ('amendment_reason', models.TextField(blank=True, null=True)),
                ('amended_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='records.medicalrecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=200)),
                ('result_value', models.TextField(blank=True, null=True)),
                ('reference_range', models.CharField(blank=True, max_length=100, null=True)),
                ('result_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resulted', 'Resulted'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('attachment_url', models.URLField(blank=True, max_length=500, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('lab_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.laborder')),
                ('lab_tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.medicalrecord')),
            ],
        ),
        migrations.AddField(
            model_name='laborder',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.medicalrecord'),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icd10_code', models.CharField(max_length=10)),
                ('icd10_description', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], max_length=20)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_chronic', models.BooleanField(default=False)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'IV'), ('im', 'IM'), ('topical', 'Topical'), ('inhalation', 'Inhalation'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dispense_status', models.CharField(choices=[('pending', 'Pending'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('allergy_conflict', models.BooleanField(default=False)),
                ('allergy_override_reason', models.TextField(blank=True, null=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pulse_bpm', models.IntegerField(blank=True, null=True)),
                ('resp_rate', models.IntegerField(blank=True, null=True)),
                ('bp_systolic', models.IntegerField(blank=True, null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('spo2_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.medicalrecord')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['patient', 'record_type', '-created_at'], name='records_med_patient_4df0d9_idx'),
        ),
        migrations.CreateModel(
            name='LabTestType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=200)),
                ('specimen', models.CharField(blank=True, default='', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.labunit')),
            ],
            options={
                'unique_together': {('lab_unit', 'test_name')},
            },
        ),
        migrations.AddField(
            model_name='laborder',
            name='lab_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.labunit'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('collected', 'Specimen Collected'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='ordered', max_length=20),
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encounter_type', models.CharField(choices=[('outpatient', 'Outpatient'), ('inpatient', 'Inpatient'), ('emergency', 'Emergency'), ('follow_up', 'Follow-up'), ('consultation', 'Consultation'), ('other', 'Other')], default='outpatient', max_length=20)),
                ('encounter_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='core.department')),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_encounters', to=settings.AUTH_USER_MODEL)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('in_consultation', 'In Consultation'), ('completed', 'Completed')], default='waiting', max_length=20)),
                ('assessment_plan', models.TextField(blank=True, null=True)),
                ('chief_complaint', models.TextField(blank=True, null=True)),
                ('discharge_summary', models.TextField(blank=True, null=True)),
                ('examination_findings', models.TextField(blank=True, null=True)),
                ('hpi', models.TextField(blank=True, null=True, verbose_name='History of presenting illness')),
                ('visit_status', models.CharField(blank=True, choices=[('registered', 'Registered'), ('waiting_triage', 'Waiting for Triage'), ('waiting_doctor', 'Waiting for Doctor'), ('in_consultation', 'In Consultation'), ('sent_to_lab', 'Sent to Lab'), ('admitted', 'Admitted'), ('discharged', 'Discharged')], default='registered', max_length=30)),
            ],
            options={
                'indexes': [models.Index(fields=['patient', '-encounter_date'], name='records_enc_patient_fa1f48_idx'), models.Index(fields=['hospital', '-encounter_date'], name='records_enc_hospita_878993_idx'), models.Index(fields=['assigned_department', 'status'], name='records_enc_dept_st_idx'), models.Index(fields=['assigned_doctor', 'status'], name='records_enc_doc_st_idx')],
            },
        ),
        migrations.CreateModel(
            name='RadiologyOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_type', models.CharField(max_length=200)),
                ('attachment_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='ordered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_orders', to='records.encounter')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['hospital', '-created_at'], name='records_rad_hospita_ed4e2d_idx')],
            },
        ),
        migrations.CreateModel(
            name='NurseShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_break', 'On Break')], default='active', max_length=20)),
                ('break_start', models.DateTimeField(blank=True, null=True)),
                ('break_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hospital')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='core.ward')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handover_notes', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('critical_patients', models.ManyToManyField(blank=True, related_name='critical_alerts', to='patients.patient')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hospital')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='records.nurseshift')),
            ],
            options={
                'indexes': [models.Index(fields=['shift', '-submitted_at'], name='records_shi_shift_i_bf60b2_idx'), models.Index(fields=['hospital', '-submitted_at'], name='records_shi_hospita_24aaf4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='nurseshift',
            index=models.Index(fields=['nurse', '-shift_start'], name='records_nur_nurse_i_a5de08_idx'),
        ),
        migrations.AddIndex(
            model_name='nurseshift',
            index=models.Index(fields=['ward', 'status'], name='records_nur_ward_id_f813dd_idx'),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_handover_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='incoming_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_handover_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='note_type',
            field=models.CharField(choices=[('observation', 'Observation'), ('handover', 'Handover'), ('incident', 'Incident')], default='observation', max_length=20),
        ),
        migrations.AddField(
            model_name='nursingnote',
            name='outgoing_signed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laborder',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('collected', 'Specimen Collected'), ('in_progress', 'In Progress'), ('resulted', 'Resulted'), ('verified', 'Verified')], default='ordered', max_length=20),
        ),
        migrations.AddField(
            model_name='laborder',
            name='collection_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='resulted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EncounterDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft_data', models.JSONField(default=dict)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_encounters', to=settings.AUTH_USER_MODEL)),
                ('encounter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='records.encounter')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounter_drafts', to='patients.patient')),
            ],
            options={
                'db_table': 'records_encounter_draft',
                'indexes': [models.Index(fields=['patient', 'hospital'], name='records_enc_patient_hospital_idx'), models.Index(fields=['created_by', 'last_saved_at'], name='records_enc_user_saved_idx')],
            },
        ),
        migrations.AddField(
            model_name='shifthandover',
            name='sbar_situation',
            field=models.TextField(blank=True, default='', help_text='Current patient status, vitals, recent changes'),
        ),
        migrations.AddField(
            model_name='shifthandover',
            name='sbar_background',
            field=models.TextField(blank=True, default='', help_text='Patient history, admission reason, relevant context'),
        ),
        migrations.AddField(
            model_name='shifthandover',
            name='sbar_assessment',
            field=models.TextField(blank=True, default='', help_text='Current clinical assessment and concerns'),
        ),
        migrations.AddField(
            model_name='shifthandover',
            name='sbar_recommendation',
            field=models.TextField(blank=True, default='', help_text='Recommended actions for incoming nurse'),
        ),
        migrations.AddField(
            model_name='shifthandover',
            name='incoming_nurse',
            field=models.ForeignKey(blank=True, help_text='Incoming nurse assigned to receive this handover', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shifthandover',
            name='incoming_acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='Incoming nurse acknowledgement timestamp (second signature)', null=True),
        ),
        migrations.AddField(
            model_name='shifthandover',
            name='outgoing_signed_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Outgoing nurse submission timestamp', null=True),
        ),
        migrations.AddIndex(
            model_name='shifthandover',
            index=models.Index(fields=['incoming_nurse', 'incoming_acknowledged_at'], name='records_shifthandover_incoming_ack_idx'),
        ),
        migrations.CreateModel(
            name='EncounterTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('personal', 'Personal'), ('shared', 'Shared')], default='personal', max_length=20)),
                ('chief_complaint_template', models.TextField(blank=True)),
                ('hpi_template', models.TextField(blank=True)),
                ('examination_template', models.TextField(blank=True)),
                ('assessment_template', models.TextField(blank=True)),
                ('default_diagnoses', models.JSONField(blank=True, default=list)),
                ('default_prescriptions', models.JSONField(blank=True, default=list)),
                ('specialty', models.CharField(blank=True, help_text='Medical specialty this template is for', max_length=100)),
                ('encounter_type', models.CharField(blank=True, help_text='Type of encounter (outpatient, emergency, etc)', max_length=50)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'encounter_template',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='shifthandover',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RenameIndex(
            model_name='encounterdraft',
            new_name='records_enc_patient_c3178a_idx',
            old_name='records_enc_patient_hospital_idx',
        ),
        migrations.RenameIndex(
            model_name='encounterdraft',
            new_name='records_enc_created_888c7f_idx',
            old_name='records_enc_user_saved_idx',
        ),
        migrations.RenameIndex(
            model_name='shifthandover',
            new_name='records_shi_incomin_adef31_idx',
            old_name='records_shifthandover_incoming_ack_idx',
        ),
        migrations.AlterField(
            model_name='nursingnote',
            name='outgoing_signed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shifthandover',
            name='critical_patients',
            field=models.ManyToManyField(blank=True, related_name='critical_handover_alerts', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='shifthandover',
            name='handover_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shifthandover',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encountertemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounter_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encountertemplate',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounter_templates', to='core.hospital'),
        ),
        migrations.AddIndex(
            model_name='encountertemplate',
            index=models.Index(fields=['hospital', 'template_type', 'is_active'], name='encounter_t_hospita_461e16_idx'),
        ),
        migrations.AddIndex(
            model_name='encountertemplate',
            index=models.Index(fields=['created_by', 'is_active'], name='encounter_t_created_9d18b1_idx'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='version',
            field=models.IntegerField(default=1, help_text='Version for optimistic locking'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laborder',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.hospital'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='ordering_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_lab_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='laborder',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='laborder',
            name='version',
            field=models.IntegerField(default=1, help_text='Version for optimistic locking'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.hospital'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='version',
            field=models.IntegerField(default=1, help_text='Version for optimistic locking'),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('medication', 'Medication Error'), ('fall', 'Patient Fall'), ('procedure', 'Procedure Related'), ('equipment', 'Equipment Failure'), ('communication', 'Communication Error'), ('documentation', 'Documentation Error'), ('infection', 'Infection Control'), ('security', 'Security/Safety'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('near_miss', 'Near Miss'), ('minor', 'Minor - No Harm'), ('moderate', 'Moderate'), ('serious', 'Serious'), ('critical', 'Critical/Death')], max_length=20)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_review', 'Under Review'), ('investigated', 'Investigated'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=20)),
                ('incident_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('immediate_actions', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('administered_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('was_refused', models.BooleanField(default=False, help_text='True if patient refused the medication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'records_medication_administration',
                'ordering': ['-administered_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('route', models.CharField(blank=True, max_length=50)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-use_count', '-last_used_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='encounter',
            options={'ordering': ['-encounter_date']},
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['hospital', 'status'], name='enc_hospital_status_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['hospital', '-created_at'], name='lab_hospital_created_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['hospital', 'status'], name='lab_hospital_status_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['lab_unit', 'urgency', '-created_at'], name='lab_unit_urgency_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['ordering_doctor', 'status'], name='lab_doctor_status_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['hospital', '-created_at'], name='rx_hospital_created_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['hospital', 'status'], name='rx_hospital_status_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', '-created_at'], name='rx_patient_created_idx'),
        ),
        migrations.AlterModelTable(
            name='encounter',
            table='encounter',
        ),
        migrations.AddField(
            model_name='prescriptionfavorite',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='administered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital'),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='records.prescription'),
        ),
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital'),
        ),
        migrations.AddField(
            model_name='incident',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='incident',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ward'),
        ),
        migrations.AlterUniqueTogether(
            name='prescriptionfavorite',
            unique_together={('doctor', 'drug_name', 'dosage', 'frequency')},
        ),
        migrations.AddIndex(
            model_name='medicationadministration',
            index=models.Index(fields=['prescription', '-administered_at'], name='records_med_prescri_34a297_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationadministration',
            index=models.Index(fields=['patient', '-administered_at'], name='records_med_patient_a46542_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationadministration',
            index=models.Index(fields=['hospital', '-administered_at'], name='records_med_hospita_12fcac_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['hospital', 'status'], name='records_inc_hospita_1204a7_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['hospital', 'severity'], name='records_inc_hospita_6fe298_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['created_at'], name='records_inc_created_5ed5f1_idx'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when medication was dispensed', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, help_text='Pharmacy technician who dispensed medication', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Quantity dispensed', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispense_notes',
            field=models.TextField(blank=True, help_text='Pharmacy dispensing notes', null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='priority',
            field=models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', help_text='Prescription priority level', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='drug_interaction_checked',
            field=models.BooleanField(default=False, help_text='Whether drug interactions were checked'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='drug_interactions',
            field=models.JSONField(blank=True, help_text='Detected drug-drug interactions', null=True),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['hospital', 'status', 'priority', '-created_at'], name='rx_pharmacy_queue_idx'),
        ),
        migrations.CreateModel(
            name='MedicationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField(help_text='When medication should be given')),
                ('actual_time', models.DateTimeField(blank=True, help_text='When medication was actually administered', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('administered', 'Administered'), ('missed', 'Missed'), ('held', 'Held'), ('refused', 'Refused')], default='scheduled', help_text='Current status of the scheduled dose', max_length=20)),
                ('hold_reason', models.TextField(blank=True, help_text='Reason for holding the medication', null=True)),
                ('refused_reason', models.TextField(blank=True, help_text='Reason patient refused medication', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional administration notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='records.prescription')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_schedules', to='patients.patient')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_schedules', to='core.hospital')),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'records_medication_schedule',
                'ordering': ['scheduled_time'],
                'indexes': [models.Index(fields=['hospital', 'scheduled_time', 'status'], name='mar_hospital_sched_idx'), models.Index(fields=['patient', 'scheduled_time'], name='mar_patient_sched_idx')],
            },
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "enc_hospital_created_idx" ON "encounter" ("hospital_id", "encounter_date" DESC)',
            reverse_sql='DROP INDEX IF EXISTS "enc_hospital_created_idx"',
            state_operations=[migrations.AddIndex(
                model_name='encounter',
                index=models.Index(fields=['hospital', '-encounter_date'], name='enc_hospital_created_idx'),
            )],
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "enc_hospital_status_idx" ON "encounter" ("hospital_id", "status")',
            reverse_sql='DROP INDEX IF EXISTS "enc_hospital_status_idx"',
            state_operations=[migrations.AddIndex(
                model_name='encounter',
                index=models.Index(fields=['hospital', 'status'], name='enc_hospital_status_idx'),
            )],
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "enc_patient_date_idx" ON "encounter" ("patient_id", "encounter_date" DESC)',
            reverse_sql='DROP INDEX IF EXISTS "enc_patient_date_idx"',
            state_operations=[migrations.AddIndex(
                model_name='encounter',
                index=models.Index(fields=['patient', '-encounter_date'], name='enc_patient_date_idx'),
            )],
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "enc_doctor_status_idx" ON "encounter" ("assigned_doctor_id", "status")',
            reverse_sql='DROP INDEX IF EXISTS "enc_doctor_status_idx"',
            state_operations=[migrations.AddIndex(
                model_name='encounter',
                index=models.Index(fields=['assigned_doctor', 'status'], name='enc_doctor_status_idx'),
            )],
        ),
        migrations.RemoveIndex(
            model_name='encounter',
            name='records_enc_patient_fa1f48_idx',
        ),
        migrations.RemoveIndex(
            model_name='encounter',
            name='records_enc_hospita_878993_idx',
        ),
        migrations.RemoveIndex(
            model_name='encounter',
            name='records_enc_dept_st_idx',
        ),
        migrations.RemoveIndex(
            model_name='encounter',
            name='records_enc_doc_st_idx',
        ),
        migrations.AddField(
            model_name='encounter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='icd10_description',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300)),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='notes',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='assessment_plan',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='chief_complaint',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='discharge_summary',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='examination_findings',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='hpi',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True, verbose_name='History of presenting illness')),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='notes',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='result_value',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='nursingnote',
            name='content',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
        migrations.AlterField(
            model_name='vital',
            name='bmi',
            field=django_cryptography.fields.encrypt(models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
        ),
        migrations.AlterField(
            model_name='vital',
            name='bp_diastolic',
            field=django_cryptography.fields.encrypt(models.IntegerField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='vital',
            name='bp_systolic',
            field=django_cryptography.fields.encrypt(models.IntegerField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='vital',
            name='height_cm',
            field=django_cryptography.fields.encrypt(models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
        ),
        migrations.AlterField(
            model_name='vital',
            name='pulse_bpm',
            field=django_cryptography.fields.encrypt(models.IntegerField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='vital',
            name='resp_rate',
            field=django_cryptography.fields.encrypt(models.IntegerField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='vital',
            name='spo2_percent',
            field=django_cryptography.fields.encrypt(models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
        ),
        migrations.AlterField(
            model_name='vital',
            name='temperature_c',
            field=django_cryptography.fields.encrypt(models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
        ),
        migrations.AlterField(
            model_name='vital',
            name='weight_kg',
            field=django_cryptography.fields.encrypt(models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['icd10_code'], name='records_dia_icd10_c_86530e_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyorder',
            index=models.Index(fields=['patient', '-created_at'], name='records_rad_patient_9db89a_idx'),
        ),
    ]
