# Generated by Django 6.0.2 on 2026-03-04 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_blueprint_alerts_encounters'),
        ('patients', '0001_blueprint_alerts_encounters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=200)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('diagnosis', 'Diagnosis'), ('prescription', 'Prescription'), ('lab_result', 'Lab Result'), ('vital_signs', 'Vital Signs'), ('nursing_note', 'Nursing Note'), ('allergy', 'Allergy')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record_version', models.IntegerField(default=0)),
                ('is_amended', models.BooleanField(default=False)),
                ('amendment_reason', models.TextField(blank=True, null=True)),
                ('amended_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amendments', to='records.medicalrecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=200)),
                ('result_value', models.TextField(blank=True, null=True)),
                ('reference_range', models.CharField(blank=True, max_length=100, null=True)),
                ('result_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resulted', 'Resulted'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('attachment_url', models.URLField(blank=True, max_length=500, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('lab_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.laborder')),
                ('lab_tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.medicalrecord')),
            ],
        ),
        migrations.AddField(
            model_name='laborder',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.medicalrecord'),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('icd10_code', models.CharField(max_length=10)),
                ('icd10_description', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], max_length=20)),
                ('onset_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_chronic', models.BooleanField(default=False)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'IV'), ('im', 'IM'), ('topical', 'Topical'), ('inhalation', 'Inhalation'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dispense_status', models.CharField(choices=[('pending', 'Pending'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('allergy_conflict', models.BooleanField(default=False)),
                ('allergy_override_reason', models.TextField(blank=True, null=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Vital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pulse_bpm', models.IntegerField(blank=True, null=True)),
                ('resp_rate', models.IntegerField(blank=True, null=True)),
                ('bp_systolic', models.IntegerField(blank=True, null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('spo2_percent', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='records.medicalrecord')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['patient', 'record_type', '-created_at'], name='records_med_patient_4df0d9_idx'),
        ),
    ]
