# Generated by Django 4.2.29 on 2026-03-05 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_workflow_encounter_lab'),
    ]

    operations = [
        # Rename indexes were removed - these indexes don't exist on the Encounter model
        # migrations.RenameIndex(
        #     model_name='encounter',
        #     new_name='records_enc_assigne_51c098_idx',
        #     old_name='records_enc_dept_st_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='encounter',
        #     new_name='records_enc_assigne_336884_idx',
        #     old_name='records_enc_doc_st_idx',
        # ),
    ]
