# Generated by Django 4.2.29 on 2026-03-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_rename_records_enc_dept_st_idx_records_enc_assigne_51c098_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='assessment_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='chief_complaint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='discharge_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='examination_findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='hpi',
            field=models.TextField(blank=True, null=True, verbose_name='History of presenting illness'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='visit_status',
            field=models.CharField(blank=True, choices=[('registered', 'Registered'), ('waiting_triage', 'Waiting for Triage'), ('waiting_doctor', 'Waiting for Doctor'), ('in_consultation', 'In Consultation'), ('sent_to_lab', 'Sent to Lab'), ('admitted', 'Admitted'), ('discharged', 'Discharged')], default='registered', max_length=30),
        ),
    ]
