# Generated by Django 4.2.29 on 2026-03-05 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_invoice_billing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0005_invoice_billing'),
        ('records', '0005_clinical_docs_visit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologyOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('study_type', models.CharField(max_length=200)),
                ('attachment_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='ordered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_orders', to='records.encounter')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['hospital', '-created_at'], name='records_rad_hospita_ed4e2d_idx')],
            },
        ),
    ]
