# Generated by Django 4.2.29 on 2026-03-07 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_superadminhospitalaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0005_invoice_billing'),
        ('records', '0006_radiology_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseShift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_break', 'On Break')], default='active', max_length=20)),
                ('break_start', models.DateTimeField(blank=True, null=True)),
                ('break_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hospital')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts', to='core.ward')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handover_notes', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('critical_patients', models.ManyToManyField(blank=True, related_name='critical_alerts', to='patients.patient')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hospital')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='records.nurseshift')),
            ],
            options={
                'indexes': [models.Index(fields=['shift', '-submitted_at'], name='records_shi_shift_i_bf60b2_idx'), models.Index(fields=['hospital', '-submitted_at'], name='records_shi_hospita_24aaf4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='nurseshift',
            index=models.Index(fields=['nurse', '-shift_start'], name='records_nur_nurse_i_a5de08_idx'),
        ),
        migrations.AddIndex(
            model_name='nurseshift',
            index=models.Index(fields=['ward', 'status'], name='records_nur_ward_id_f813dd_idx'),
        ),
    ]
