# Generated by Django 4.2.29 on 2026-04-06 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_add_hospital_ai_enabled'),
        ('patients', '0008_encrypt_phi_fields'),
        ('records', '0011_sbar_handover_signatures'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('template_type', models.CharField(choices=[('personal', 'Personal'), ('shared', 'Shared')], default='personal', max_length=20)),
                ('chief_complaint_template', models.TextField(blank=True)),
                ('hpi_template', models.TextField(blank=True)),
                ('examination_template', models.TextField(blank=True)),
                ('assessment_template', models.TextField(blank=True)),
                ('default_diagnoses', models.JSONField(blank=True, default=list)),
                ('default_prescriptions', models.JSONField(blank=True, default=list)),
                ('specialty', models.CharField(blank=True, help_text='Medical specialty this template is for', max_length=100)),
                ('encounter_type', models.CharField(blank=True, help_text='Type of encounter (outpatient, emergency, etc)', max_length=50)),
                ('usage_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'encounter_template',
                'ordering': ['-usage_count', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='shifthandover',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RenameIndex(
            model_name='encounterdraft',
            new_name='records_enc_patient_c3178a_idx',
            old_name='records_enc_patient_hospital_idx',
        ),
        migrations.RenameIndex(
            model_name='encounterdraft',
            new_name='records_enc_created_888c7f_idx',
            old_name='records_enc_user_saved_idx',
        ),
        migrations.RenameIndex(
            model_name='shifthandover',
            new_name='records_shi_incomin_adef31_idx',
            old_name='records_shifthandover_incoming_ack_idx',
        ),
        migrations.AlterField(
            model_name='nursingnote',
            name='outgoing_signed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shifthandover',
            name='critical_patients',
            field=models.ManyToManyField(blank=True, related_name='critical_handover_alerts', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='shifthandover',
            name='handover_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='shifthandover',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encountertemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounter_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encountertemplate',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounter_templates', to='core.hospital'),
        ),
        migrations.AddIndex(
            model_name='encountertemplate',
            index=models.Index(fields=['hospital', 'template_type', 'is_active'], name='encounter_t_hospita_461e16_idx'),
        ),
        migrations.AddIndex(
            model_name='encountertemplate',
            index=models.Index(fields=['created_by', 'is_active'], name='encounter_t_created_9d18b1_idx'),
        ),
    ]
