# Generated by Django 4.2.29 on 2026-04-06 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_announcement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0010_add_walkin_fields'),
        ('records', '0013_add_version_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('medication', 'Medication Error'), ('fall', 'Patient Fall'), ('procedure', 'Procedure Related'), ('equipment', 'Equipment Failure'), ('communication', 'Communication Error'), ('documentation', 'Documentation Error'), ('infection', 'Infection Control'), ('security', 'Security/Safety'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('near_miss', 'Near Miss'), ('minor', 'Minor - No Harm'), ('moderate', 'Moderate'), ('serious', 'Serious'), ('critical', 'Critical/Death')], max_length=20)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('under_review', 'Under Review'), ('investigated', 'Investigated'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=20)),
                ('incident_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('immediate_actions', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('administered_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('was_refused', models.BooleanField(default=False, help_text='True if patient refused the medication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'records_medication_administration',
                'ordering': ['-administered_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('route', models.CharField(blank=True, max_length=50)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-use_count', '-last_used_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='encounter',
            options={'ordering': ['-encounter_date']},
        ),
        # RenameIndex operations removed - these indexes don't exist on fresh DB creation
        # migrations.RenameIndex(
        #     model_name='encounter',
        #     new_name='encounter_patient_0dba2d_idx',
        #     old_name='records_enc_patient_fa1f48_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='encounter',
        #     new_name='encounter_hospita_62b1da_idx',
        #     old_name='records_enc_hospita_878993_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='encounter',
        #     new_name='encounter_assigne_db8dac_idx',
        #     old_name='records_enc_assigne_51c098_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='encounter',
        #     new_name='encounter_assigne_aaf983_idx',
        #     old_name='records_enc_assigne_336884_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='encounter',
        #     new_name='enc_hospital_created_idx',
        #     old_name='records_enc_hospita_878993_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='encounter',
        #     new_name='enc_patient_date_idx',
        #     old_name='records_enc_patient_fa1f48_idx',
        # ),
        # migrations.RenameIndex(
        #     model_name='encounter',
        #     new_name='enc_doctor_status_idx',
        #     old_name='records_enc_assigne_336884_idx',
        # ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['hospital', 'status'], name='enc_hospital_status_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['hospital', '-created_at'], name='lab_hospital_created_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['hospital', 'status'], name='lab_hospital_status_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['lab_unit', 'urgency', '-created_at'], name='lab_unit_urgency_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['ordering_doctor', 'status'], name='lab_doctor_status_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['hospital', '-created_at'], name='rx_hospital_created_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['hospital', 'status'], name='rx_hospital_status_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['patient', '-created_at'], name='rx_patient_created_idx'),
        ),
        migrations.AlterModelTable(
            name='encounter',
            table='encounter',
        ),
        migrations.AddField(
            model_name='prescriptionfavorite',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='administered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_medications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital'),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='records.prescription'),
        ),
        migrations.AddField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital'),
        ),
        migrations.AddField(
            model_name='incident',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='incident',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ward'),
        ),
        migrations.AlterUniqueTogether(
            name='prescriptionfavorite',
            unique_together={('doctor', 'drug_name', 'dosage', 'frequency')},
        ),
        migrations.AddIndex(
            model_name='medicationadministration',
            index=models.Index(fields=['prescription', '-administered_at'], name='records_med_prescri_34a297_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationadministration',
            index=models.Index(fields=['patient', '-administered_at'], name='records_med_patient_a46542_idx'),
        ),
        migrations.AddIndex(
            model_name='medicationadministration',
            index=models.Index(fields=['hospital', '-administered_at'], name='records_med_hospita_12fcac_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['hospital', 'status'], name='records_inc_hospita_1204a7_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['hospital', 'severity'], name='records_inc_hospita_6fe298_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['created_at'], name='records_inc_created_5ed5f1_idx'),
        ),
    ]
