# Generated by Django 4.2.29 on 2026-04-18 01:17
# Create the final index state for Encounter model

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_medication_schedule'),
    ]

    operations = [
        # Add named indexes with their final names to replace old auto-named indexes
        # Use IF NOT EXISTS for SQLite compatibility
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "enc_hospital_created_idx" ON "encounter" ("hospital_id", "encounter_date" DESC)',
            reverse_sql='DROP INDEX IF EXISTS "enc_hospital_created_idx"',
            state_operations=[
                migrations.AddIndex(
                    model_name='encounter',
                    index=models.Index(fields=['hospital', '-encounter_date'], name='enc_hospital_created_idx'),
                ),
            ]
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "enc_hospital_status_idx" ON "encounter" ("hospital_id", "status")',
            reverse_sql='DROP INDEX IF EXISTS "enc_hospital_status_idx"',
            state_operations=[
                migrations.AddIndex(
                    model_name='encounter',
                    index=models.Index(fields=['hospital', 'status'], name='enc_hospital_status_idx'),
                ),
            ]
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "enc_patient_date_idx" ON "encounter" ("patient_id", "encounter_date" DESC)',
            reverse_sql='DROP INDEX IF EXISTS "enc_patient_date_idx"',
            state_operations=[
                migrations.AddIndex(
                    model_name='encounter',
                    index=models.Index(fields=['patient', '-encounter_date'], name='enc_patient_date_idx'),
                ),
            ]
        ),
        migrations.RunSQL(
            sql='CREATE INDEX IF NOT EXISTS "enc_doctor_status_idx" ON "encounter" ("assigned_doctor_id", "status")',
            reverse_sql='DROP INDEX IF EXISTS "enc_doctor_status_idx"',
            state_operations=[
                migrations.AddIndex(
                    model_name='encounter',
                    index=models.Index(fields=['assigned_doctor', 'status'], name='enc_doctor_status_idx'),
                ),
            ]
        ),
    ]
