# Generated by Django 4.2.29 on 2026-04-18 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_rename_records_enc_patient_fa1f48_idx_encounter_patient_0dba2d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='encounter',
            name='records_enc_patient_fa1f48_idx',
        ),
        migrations.RemoveIndex(
            model_name='encounter',
            name='records_enc_hospita_878993_idx',
        ),
        migrations.RemoveIndex(
            model_name='encounter',
            name='records_enc_dept_st_idx',
        ),
        migrations.RemoveIndex(
            model_name='encounter',
            name='records_enc_doc_st_idx',
        ),
    ]
