# Generated by Django 4.2.29 on 2026-04-24 14:25

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0018_remove_encounter_records_enc_patient_fa1f48_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='icd10_description',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=300)),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='notes',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='assessment_plan',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='chief_complaint',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='discharge_summary',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='examination_findings',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='hpi',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True, verbose_name='History of presenting illness')),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='notes',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='labresult',
            name='result_value',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='nursingnote',
            name='content',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
        migrations.AlterField(
            model_name='vital',
            name='bmi',
            field=django_cryptography.fields.encrypt(models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
        ),
        migrations.AlterField(
            model_name='vital',
            name='bp_diastolic',
            field=django_cryptography.fields.encrypt(models.IntegerField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='vital',
            name='bp_systolic',
            field=django_cryptography.fields.encrypt(models.IntegerField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='vital',
            name='height_cm',
            field=django_cryptography.fields.encrypt(models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
        ),
        migrations.AlterField(
            model_name='vital',
            name='pulse_bpm',
            field=django_cryptography.fields.encrypt(models.IntegerField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='vital',
            name='resp_rate',
            field=django_cryptography.fields.encrypt(models.IntegerField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='vital',
            name='spo2_percent',
            field=django_cryptography.fields.encrypt(models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
        ),
        migrations.AlterField(
            model_name='vital',
            name='temperature_c',
            field=django_cryptography.fields.encrypt(models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
        ),
        migrations.AlterField(
            model_name='vital',
            name='weight_kg',
            field=django_cryptography.fields.encrypt(models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['icd10_code'], name='records_dia_icd10_c_86530e_idx'),
        ),
        migrations.AddIndex(
            model_name='radiologyorder',
            index=models.Index(fields=['patient', '-created_at'], name='records_rad_patient_9db89a_idx'),
        ),
    ]
