# Generated by Django 4.2.29 on 2026-05-14 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0014_patientconsent'),
        ('core', '0031_add_totp_grace_period'),
        ('records', '0001_squashed_0019_encounter_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('diagnosis', 'Diagnosis'), ('prescription', 'Prescription'), ('lab_result', 'Lab Result'), ('vital_signs', 'Vital Signs'), ('nursing_note', 'Nursing Note'), ('allergy', 'Allergy'), ('immunisation', 'Immunisation'), ('procedure_note', 'Procedure Note'), ('notifiable_disease', 'Notifiable Disease')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProcedureNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('procedure_name', models.CharField(max_length=255)),
                ('anaesthesia_type', models.CharField(blank=True, max_length=100, null=True)),
                ('findings', models.TextField()),
                ('procedure_details', models.TextField()),
                ('complications', models.TextField(blank=True, null=True)),
                ('post_op_instructions', models.TextField(blank=True, null=True)),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedure_notes_as_assistant', to=settings.AUTH_USER_MODEL)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_note', to='records.medicalrecord')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedure_notes_as_surgeon', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotifiableDisease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=200)),
                ('ghs_case_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('reported_to_ghs', models.BooleanField(default=False)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=100, null=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notifiable_disease', to='records.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Immunisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=200)),
                ('dose_number', models.IntegerField()),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('site', models.CharField(blank=True, max_length=100, null=True)),
                ('route', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='immunisation', to='records.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('spouse', 'Spouse'), ('next_of_kin', 'Next of Kin'), ('other', 'Other')], max_length=20)),
                ('is_emergency_contact', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('from_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_from', to='patients.patient')),
                ('to_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('maintenance', 'Maintenance'), ('out_of_service', 'Out of Service')], default='available', max_length=20)),
                ('last_maintenance_at', models.DateField(blank=True, null=True)),
                ('current_ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ward')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='ChronicDiseaseProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=200)),
                ('enrolled_at', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn'), ('deceased', 'Deceased')], default='active', max_length=20)),
                ('last_review_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('enrolled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chronic_programs', to='patients.patient')),
            ],
        ),
    ]
