# Generated by Django 4.2.29 on 2026-05-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0020_alter_medicalrecord_record_type_procedurenote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescribed_quantity',
            field=models.PositiveIntegerField(default=10, help_text='Total prescribed quantity'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dispense_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispensing', 'Dispensing'), ('partially_dispensed', 'Partially Dispensed'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('dispensing', 'Dispensing'), ('partially_dispensed', 'Partially Dispensed'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
