# Generated by Django 4.2.29 on 2026-05-24 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0016_invoice_invoice_number_invoice_nhis_claim_reference_and_more'),
        ('core', '0032_alter_auditlog_ip_address'),
        ('records', '0021_prescription_prescribed_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vital',
            name='avpu_score',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, choices=[('A', 'Alert'), ('V', 'Voice'), ('P', 'Pain'), ('U', 'Unresponsive')], help_text='AVPU scale score', max_length=2, null=True)),
        ),
        migrations.AddField(
            model_name='vital',
            name='gcs_score',
            field=django_cryptography.fields.encrypt(models.IntegerField(blank=True, help_text='Glasgow Coma Scale total score (3-15)', null=True)),
        ),
        migrations.AddField(
            model_name='vital',
            name='news2_score',
            field=django_cryptography.fields.encrypt(models.IntegerField(blank=True, help_text='National Early Warning Score 2 (0-20)', null=True)),
        ),
        migrations.AddField(
            model_name='vital',
            name='pain_score',
            field=django_cryptography.fields.encrypt(models.IntegerField(blank=True, help_text='Pain score on 0-10 Numeric Rating Scale', null=True)),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_type',
            field=models.CharField(choices=[('diagnosis', 'Diagnosis'), ('prescription', 'Prescription'), ('lab_result', 'Lab Result'), ('vital_signs', 'Vital Signs'), ('nursing_note', 'Nursing Note'), ('allergy', 'Allergy'), ('immunisation', 'Immunisation'), ('procedure_note', 'Procedure Note'), ('notifiable_disease', 'Notifiable Disease'), ('care_plan', 'Care Plan')], max_length=20),
        ),
        migrations.CreateModel(
            name='SocialDeterminantsOfHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('education_level', models.CharField(choices=[('none', 'No formal education'), ('primary', 'Primary Education'), ('secondary', 'Secondary/High School'), ('tertiary', 'Tertiary/University'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('water_access', models.CharField(choices=[('piped_indoor', 'Piped water (indoor)'), ('piped_yard', 'Piped water (yard/borehole)'), ('public_tap', 'Public tap/standpipe'), ('surface_water', 'Surface water (river/stream)'), ('tanker', 'Water tanker/vendor')], default='piped_indoor', max_length=20)),
                ('sanitation', models.CharField(choices=[('flush_toilet', 'Flush toilet (private)'), ('shared_latrine', 'Shared toilet/latrine'), ('public_toilet', 'Public toilet'), ('open_defecation', 'No facility/open defecation')], default='flush_toilet', max_length=20)),
                ('distance_to_facility_km', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('has_health_insurance', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sdoh', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ImagingStudy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('available', 'Available'), ('cancelled', 'Cancelled'), ('entered-in-error', 'Entered in Error')], default='available', max_length=20)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('modality', models.CharField(help_text='e.g., CT, MR, US, DX', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('number_of_series', models.PositiveIntegerField(default=1)),
                ('number_of_instances', models.PositiveIntegerField(default=1)),
                ('series', models.JSONField(blank=True, default=list, help_text='List of series details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imaging_studies', to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_studies', to='patients.patient')),
                ('radiology_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_studies', to='records.radiologyorder')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('sibling', 'Sibling'), ('grandparent', 'Grandparent'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('other', 'Other')], max_length=30)),
                ('relative_name', models.CharField(blank=True, max_length=100, null=True)),
                ('condition_name', models.CharField(help_text='Condition name (e.g., Diabetes, Sickle Cell)', max_length=200)),
                ('icd10_code', models.CharField(blank=True, max_length=10, null=True)),
                ('onset_age', models.IntegerField(blank=True, null=True)),
                ('is_deceased', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_histories', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('completed', 'Completed'), ('entered-in-error', 'Entered in Error'), ('cancelled', 'Cancelled'), ('unknown', 'Unknown')], default='active', max_length=20)),
                ('intent', models.CharField(choices=[('proposal', 'Proposal'), ('plan', 'Plan'), ('order', 'Order'), ('option', 'Option')], default='plan', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('goals', models.JSONField(blank=True, default=list, help_text='List of structured treatment goals')),
                ('activities', models.JSONField(blank=True, default=list, help_text='List of activities, tasks, or milestones')),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_plan', to='records.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='DHIMS2Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(help_text='Format YYYY-MM', max_length=7)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('indicators', models.JSONField(default=dict, help_text='Indicator counts payload')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('response_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dhims2_reports', to='core.hospital')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_dhims2_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('hospital', 'month')},
            },
        ),
    ]
