# Generated by Django 4.2.29 on 2026-05-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0022_vital_avpu_score_vital_gcs_score_vital_news2_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dispense_workflow',
            field=models.CharField(choices=[('internal', 'Internal Pharmacy'), ('external_mpharma', 'External mPharma')], default='internal', help_text='Dispense routing workflow (internal or external_mpharma)', max_length=50),
        ),
    ]
