# Generated by Django 4.2.29 on 2026-06-03 16:33

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0024_medicalrecord_retention_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='dispense_workflow',
        ),
        migrations.AlterField(
            model_name='careplan',
            name='activities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='careplan',
            name='goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='dhims2report',
            name='indicators',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='familyhistory',
            name='condition_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='imagingstudy',
            name='series',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='vital',
            name='gcs_score',
            field=django_cryptography.fields.encrypt(models.IntegerField(blank=True, help_text='Glasgow Coma Scale total (3-15)', null=True)),
        ),
        migrations.AlterField(
            model_name='vital',
            name='pain_score',
            field=django_cryptography.fields.encrypt(models.IntegerField(blank=True, help_text='Pain score 0-10 (NRS)', null=True)),
        ),
    ]
