# Generated by Django 4.2.29 — dependency corrected to point at 0025.

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0025_remove_prescription_dispense_workflow_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='chronicdiseaseprogram',
            managers=[
                ('tenant_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='dhims2report',
            managers=[
                ('tenant_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='encounter',
            managers=[
                ('tenant_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='incident',
            managers=[
                ('tenant_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='laborder',
            managers=[
                ('tenant_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='medicalrecord',
            managers=[
                ('tenant_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='prescription',
            managers=[
                ('tenant_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='radiologyorder',
            managers=[
                ('tenant_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
