[pytest]
DJANGO_SETTINGS_MODULE = medsync_backend.settings
pythonpath = .
python_files = test_*.py
addopts = -v --tb=short --nomigrations
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::pytest.PytestUnknownMarkWarning
