# Generated by Django 6.0.2 on 2026-03-04 02:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('patients', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPatient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=10)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1)),
            ],
            options={
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='interop_glo_last_na_949595_idx'), models.Index(fields=['national_id'], name='interop_glo_nationa_1443d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='FacilityPatient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_patient_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_patients', to='core.hospital')),
                ('patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_profile', to='patients.patient')),
                ('global_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_profiles', to='interop.globalpatient')),
            ],
        ),
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('SUMMARY', 'Summary'), ('FULL_RECORD', 'Full Record')], max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('granted_to_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents_received', to='core.hospital')),
                ('global_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='interop.globalpatient')),
            ],
        ),
        migrations.CreateModel(
            name='BreakGlassLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('global_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_glass_logs', to='interop.globalpatient')),
            ],
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_sent', to='core.hospital')),
                ('global_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='interop.globalpatient')),
                ('to_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='core.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True)),
                ('diagnosis', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('facility_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encounters', to='interop.facilitypatient')),
            ],
            options={
                'indexes': [models.Index(fields=['facility_patient', '-created_at'], name='interop_enc_facilit_6699eb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='facilitypatient',
            index=models.Index(fields=['facility', 'global_patient'], name='interop_fac_facilit_9859bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facilitypatient',
            unique_together={('facility', 'global_patient')},
        ),
        migrations.AddIndex(
            model_name='consent',
            index=models.Index(fields=['global_patient', 'granted_to_facility', 'is_active'], name='interop_con_global__bbf531_idx'),
        ),
        migrations.AddIndex(
            model_name='breakglasslog',
            index=models.Index(fields=['global_patient', 'created_at'], name='interop_bre_global__303514_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['to_facility', 'status'], name='interop_ref_to_faci_c2e37f_idx'),
        ),
    ]
