# Generated by Django 6.0.2 on 2026-03-04 10:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('interop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='consent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='interop.consent'),
        ),
        migrations.AddField(
            model_name='referral',
            name='record_ids_to_share',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of record UUIDs to share with receiving facility.'),
        ),
        migrations.CreateModel(
            name='SharedRecordAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('accessing_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.hospital')),
                ('global_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_access_logs', to='interop.globalpatient')),
            ],
            options={
                'indexes': [models.Index(fields=['global_patient', '-created_at'], name='interop_sha_global__2c0a52_idx')],
            },
        ),
    ]
