# Generated by Django 4.2.29 on 2026-03-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0002_hie_shared_record_access_consent_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpatient',
            name='ghana_health_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='globalpatient',
            name='nhis_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='globalpatient',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
