# Generated by Django 4.2.29 on 2026-03-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0003_global_patient_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakglasslog',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Time when this break-glass access expires (15 minutes from creation by default)', null=True),
        ),
    ]
