# Generated by Django 4.2.29 on 2026-03-25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("interop", "0004_add_break_glass_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="breakglasslog",
            name="reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="breakglasslog",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="breakglasslog",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="core.user",
            ),
        ),
        migrations.AddField(
            model_name="breakglasslog",
            name="excessive_usage",
            field=models.BooleanField(
                default=False,
                help_text="Set true when break-glass usage is flagged as potentially abusive.",
            ),
        ),
    ]

