# Generated by Django 4.2.29 on 2026-03-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interop", "0005_breakglass_review_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="breakglasslog",
            name="reason_code",
            field=models.CharField(
                choices=[
                    ("life_threatening_emergency", "Life-threatening emergency"),
                    ("unconscious_patient", "Unconscious patient / no consent possible"),
                    ("critical_time_sensitive_care", "Critical time-sensitive care"),
                    ("mass_casualty_event", "Mass casualty event"),
                    ("other_emergency", "Other emergency"),
                ],
                default="other_emergency",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="breakglasslog",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Time when this break-glass access expires (4 hours from creation by default)",
                null=True,
            ),
        ),
    ]

