# Generated by Django 4.2.29 on 2026-04-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0006_breakglass_reason_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='version',
            field=models.IntegerField(default=1, help_text='Version for optimistic locking'),
        ),
    ]
