# Generated by Django 4.2.29 on 2026-04-24 14:25

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0007_add_version_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpatient',
            name='date_of_birth',
            field=django_cryptography.fields.encrypt(models.DateField()),
        ),
        migrations.AlterField(
            model_name='globalpatient',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(blank=True, max_length=254, null=True)),
        ),
        migrations.AlterField(
            model_name='globalpatient',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
        migrations.AlterField(
            model_name='globalpatient',
            name='ghana_health_id',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True)),
        ),
        migrations.AlterField(
            model_name='globalpatient',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
        migrations.AlterField(
            model_name='globalpatient',
            name='national_id',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True, unique=True)),
        ),
        migrations.AlterField(
            model_name='globalpatient',
            name='nhis_number',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True)),
        ),
        migrations.AlterField(
            model_name='globalpatient',
            name='passport_number',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True)),
        ),
        migrations.AlterField(
            model_name='globalpatient',
            name='phone',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=20, null=True)),
        ),
        migrations.AddIndex(
            model_name='facilitypatient',
            index=models.Index(fields=['local_patient_id'], name='interop_fac_local_p_b46b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='globalpatient',
            index=models.Index(fields=['ghana_health_id'], name='interop_glo_ghana_h_c5fbc6_idx'),
        ),
        migrations.AddIndex(
            model_name='globalpatient',
            index=models.Index(fields=['nhis_number'], name='interop_glo_nhis_nu_00a778_idx'),
        ),
        migrations.AddIndex(
            model_name='globalpatient',
            index=models.Index(fields=['passport_number'], name='interop_glo_passpor_dc3395_idx'),
        ),
    ]
