# Generated by Django 4.2.29 on 2026-05-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0008_alter_globalpatient_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
