# Generated by Django 4.2.29 on 2026-05-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0009_alter_referral_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpatient',
            name='data_residency_country',
            field=models.CharField(db_index=True, default='GH', help_text="ISO 3166-1 alpha-2 country code for the patient's data residency. Defaults to 'GH' (Ghana). Determines which facilities are allowed to access cross-facility records.", max_length=2),
        ),
        migrations.AddField(
            model_name='globalpatient',
            name='data_residency_locked',
            field=models.BooleanField(default=False, help_text='When True, cross-facility record sharing is restricted to facilities within the data_residency_country. Access from outside the residency country will be blocked regardless of consent. Set True for patients who have explicitly requested data localisation or when required by law (e.g. NDPA 2012 § 36 — transfer restriction).'),
        ),
        migrations.AddIndex(
            model_name='globalpatient',
            index=models.Index(fields=['data_residency_country', 'data_residency_locked'], name='interop_glo_data_re_f70d80_idx'),
        ),
    ]
