# Generated by Django 4.2.29 on 2026-05-24 21:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0011_alter_referral_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. HIV, MentalHealth, Condition, Observation', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='consent',
            name='excluded_scopes',
            field=models.ManyToManyField(blank=True, related_name='consents_excluded', to='interop.consentscope'),
        ),
    ]
