# Generated by Django 4.2.29 on 2026-06-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0013_consent_withdrawal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='consented_encounter_ids',
            field=models.JSONField(blank=True, default=list, help_text='Scope this consent to only these encounter IDs.'),
        ),
        migrations.AddField(
            model_name='consent',
            name='consented_record_ids',
            field=models.JSONField(blank=True, default=list, help_text='Scope this consent to only these record IDs.'),
        ),
        migrations.AddField(
            model_name='referral',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='encounter_ids_to_share',
            field=models.JSONField(blank=True, default=list, help_text='Optional list of encounter UUIDs to share with receiving facility.'),
        ),
        migrations.AddField(
            model_name='referral',
            name='is_reverse_referral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='receiving_department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('INFO_REQUESTED', 'Info Requested')], default='PENDING', max_length=20),
        ),
    ]
