# Generated by Django 4.2.29 on 2026-06-10 12:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_auditlog_action_alter_tasksubmission_task_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interop', '0014_consent_consented_encounter_ids_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Encounter',
            new_name='FacilityEncounter',
        ),
        migrations.AlterModelTable(
            name='facilityencounter',
            table='interop_encounter',
        ),
    ]
