from django.db import migrations


class Migration(migrations.Migration):
    """
    Rename interop.Encounter → FacilityEncounter to eliminate name ambiguity
    with records.Encounter.

    The explicit db_table = 'interop_encounter' on the new model means no
    physical RENAME TABLE is issued — the table stays 'interop_encounter'.
    AlterModelTable is included so Django's migration state correctly records
    the explicit db_table, keeping future autogenerated migrations clean.
    """

    dependencies = [
        ("interop", "0015_protect_referral_hospital_fks"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Encounter",
            new_name="FacilityEncounter",
        ),
        # Record the explicit db_table in migration state (no physical rename
        # because the table is already named 'interop_encounter').
        migrations.AlterModelTable(
            name="facilityencounter",
            table="interop_encounter",
        ),
    ]
