# Generated by Django 4.2.29 — AlterModelTable removed (recorded in 0016).

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('interop', '0016_rename_encounter_facilityencounter'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='facilityencounter',
            managers=[
                ('tenant_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
