# Generated by Django 4.2.29 on 2026-05-02 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    replaces = [('patients', '0001_blueprint_alerts_encounters'), ('patients', '0002_clinical_alert'), ('patients', '0003_appointment_scheduling'), ('patients', '0004_patient_identifiers_duplicates'), ('patients', '0005_invoice_billing'), ('patients', '0006_admission_bed'), ('patients', '0007_add_no_show_fields'), ('patients', '0008_encrypt_phi_fields'), ('patients', '0009_add_version_field'), ('patients', '0010_add_walkin_fields'), ('patients', '0011_emergency_triage'), ('patients', '0012_alter_appointment_chief_complaint_and_more'), ('patients', '0013_invoiceitem_appointment_updated_at_and_more')]

    initial = True

    dependencies = [
        ('core', '0006_patient_identifiers_duplicates'),
        ('core', '0003_blueprint_alerts_encounters'),
        ('core', '0013_beds'),
        ('core', '0007_invoice_billing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ghana_health_id', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=10)),
                ('phone', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=20, null=True))),
                ('national_id', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True))),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('registered_at', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hospital')),
                ('nhis_number', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True))),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PotentialDuplicate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('not_duplicate', 'Not Duplicate'), ('approved_duplicate', 'Approved Duplicate'), ('merged', 'Merged')], default='pending', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('merged_into_patient_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
                ('patient_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_candidates_a', to='patients.patient')),
                ('patient_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_candidates_b', to='patients.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['hospital', 'status'], name='patients_po_hospita_4695ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('allergen', django_cryptography.fields.encrypt(models.CharField(max_length=200))),
                ('reaction_type', django_cryptography.fields.encrypt(models.CharField(max_length=200))),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('life_threatening', 'Life Threatening')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAdmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admitted_at', models.DateTimeField(auto_now_add=True)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('discharge_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ward')),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='core.bed')),
            ],
            options={
                'indexes': [models.Index(fields=['ward', 'discharged_at'], name='adm_ward_discharged_idx'), models.Index(fields=['hospital', '-admitted_at'], name='adm_hospital_admitted_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.IntegerField(default=0)),
                ('service_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('appointment_type', models.CharField(choices=[('outpatient', 'Outpatient'), ('follow_up', 'Follow-up'), ('consultation', 'Consultation'), ('procedure', 'Procedure'), ('walk_in', 'Walk-in'), ('other', 'Other')], default='outpatient', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('no_show_marked_at', models.DateTimeField(blank=True, help_text='Time when appointment was auto-marked as no-show (null if manual or not no-show)', null=True)),
                ('no_show_override_reason', models.TextField(blank=True, help_text='Reason for unmarking a no-show (if doctor overrides)', null=True)),
                ('queue_position', models.PositiveIntegerField(blank=True, help_text='Queue position for walk-in appointments', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for visit', null=True)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', help_text='Urgency level of appointment', max_length=20)),
                ('triage_color', models.CharField(blank=True, choices=[('red', 'RED - Immediate (<5min)'), ('yellow', 'YELLOW - Urgent (<30min)'), ('green', 'GREEN - Less Urgent (<2hr)'), ('blue', 'BLUE - Non-Urgent (routine)')], help_text='Emergency triage color code (red=immediate, yellow=urgent, green=less urgent, blue=non-urgent)', max_length=10, null=True)),
                ('triage_assessed_at', models.DateTimeField(blank=True, help_text='Timestamp when triage assessment was completed', null=True)),
                ('triaged_by', models.ForeignKey(blank=True, help_text='User (doctor/nurse) who performed triage assessment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_assessments', to=settings.AUTH_USER_MODEL)),
                ('chief_complaint', models.TextField(blank=True, help_text='Primary reason for emergency visit', null=True)),
                ('triage_vitals', models.JSONField(blank=True, help_text='Vital signs captured during triage (BP, HR, RR, SpO2, temp, pain_scale)', null=True)),
                ('ed_arrival_time', models.DateTimeField(blank=True, help_text='Time patient arrived to Emergency Department', null=True)),
                ('ed_room_assignment', models.CharField(blank=True, help_text="Assigned ED room/bed (e.g., 'ED-1', 'Trauma Bay 2')", max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['hospital', 'scheduled_at'], name='patients_ap_hospita_c5cb49_idx'), models.Index(fields=['patient', '-scheduled_at'], name='patients_ap_patient_bb1c6f_idx'), models.Index(fields=['status', 'no_show_marked_at'], name='patients_ap_status_7dd8ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClinicalAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resource_type', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hospital')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['hospital', 'status', '-created_at'], name='patients_cl_hospita_d255b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_cents', models.IntegerField(default=0)),
                ('currency', models.CharField(default='GHS', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['hospital', '-created_at'], name='patients_in_hospita_cf48c3_idx'), models.Index(fields=['patient', '-created_at'], name='patients_in_patient_39a589_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['full_name'], name='patients_pa_full_na_b75abe_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_archived', 'registered_at'], name='patients_pa_is_arch_4f656a_idx'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='patients.invoice'),
        ),
    ]
