# Generated by Django 4.2.29 on 2026-03-05 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_patient_identifiers_duplicates'),
        ('patients', '0003_appointment_scheduling'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='nhis_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='PotentialDuplicate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('not_duplicate', 'Not Duplicate'), ('approved_duplicate', 'Approved Duplicate'), ('merged', 'Merged')], default='pending', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('merged_into_patient_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
                ('patient_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_candidates_a', to='patients.patient')),
                ('patient_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_candidates_b', to='patients.patient')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['hospital', 'status'], name='patients_po_hospita_4695ec_idx')],
            },
        ),
    ]
