# Generated by Django 4.2.29 on 2026-03-09 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_beds'),
        ('patients', '0005_invoice_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientadmission',
            name='bed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='core.bed'),
        ),
    ]
