# Generated by Django 4.2.29 on 2026-03-24 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_admission_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='no_show_marked_at',
            field=models.DateTimeField(blank=True, help_text='Time when appointment was auto-marked as no-show (null if manual or not no-show)', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='no_show_override_reason',
            field=models.TextField(blank=True, help_text='Reason for unmarking a no-show (if doctor overrides)', null=True),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status', 'no_show_marked_at'], name='patients_ap_status_7dd8ff_idx'),
        ),
    ]
