# Generated by Django 4.2.29 on 2026-03-27 10:30

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_add_no_show_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allergy",
            name="allergen",
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
        migrations.AlterField(
            model_name="allergy",
            name="reaction_type",
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
        migrations.AlterField(
            model_name="patient",
            name="national_id",
            field=django_cryptography.fields.encrypt(
                models.CharField(blank=True, max_length=50, null=True)
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="nhis_number",
            field=django_cryptography.fields.encrypt(
                models.CharField(blank=True, max_length=50, null=True)
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=django_cryptography.fields.encrypt(
                models.CharField(blank=True, max_length=20, null=True)
            ),
        ),
    ]
