# Generated by Django 4.2.29 on 2026-04-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_encrypt_phi_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='queue_position',
            field=models.PositiveIntegerField(blank=True, help_text='Queue position for walk-in appointments', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for visit', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='urgency',
            field=models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', help_text='Urgency level of appointment', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('outpatient', 'Outpatient'), ('follow_up', 'Follow-up'), ('consultation', 'Consultation'), ('procedure', 'Procedure'), ('walk_in', 'Walk-in'), ('other', 'Other')], default='outpatient', max_length=20),
        ),
    ]
