# Generated by Django 4.2.29 on 2026-04-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_add_version_field'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patientadmission',
            index=models.Index(fields=['ward', 'discharged_at'], name='adm_ward_discharged_idx'),
        ),
        migrations.AddIndex(
            model_name='patientadmission',
            index=models.Index(fields=['hospital', '-admitted_at'], name='adm_hospital_admitted_idx'),
        ),
    ]
