# Generated by Django 4.2.29 on 2026-04-18 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0011_emergency_triage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='chief_complaint',
            field=models.TextField(blank=True, help_text='Primary reason for emergency visit', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ed_arrival_time',
            field=models.DateTimeField(blank=True, help_text='Time patient arrived to Emergency Department', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='ed_room_assignment',
            field=models.CharField(blank=True, help_text="Assigned ED room/bed (e.g., 'ED-1', 'Trauma Bay 2')", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='triage_assessed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when triage assessment was completed', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='triage_color',
            field=models.CharField(blank=True, choices=[('red', 'RED - Immediate (<5min)'), ('yellow', 'YELLOW - Urgent (<30min)'), ('green', 'GREEN - Less Urgent (<2hr)'), ('blue', 'BLUE - Non-Urgent (routine)')], help_text='Emergency triage color code (red=immediate, yellow=urgent, green=less urgent, blue=non-urgent)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='triage_vitals',
            field=models.JSONField(blank=True, help_text='Vital signs captured during triage (BP, HR, RR, SpO2, temp, pain_scale)', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='triaged_by',
            field=models.ForeignKey(blank=True, help_text='User (doctor/nurse) who performed triage assessment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_assessments', to=settings.AUTH_USER_MODEL),
        ),
    ]
