# Generated by Django 4.2.29 on 2026-04-24 14:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_alter_appointment_chief_complaint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.IntegerField(default=0)),
                ('service_type', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='clinicalalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['patient', '-created_at'], name='patients_in_patient_39a589_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['full_name'], name='patients_pa_full_na_b75abe_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['is_archived', 'registered_at'], name='patients_pa_is_arch_4f656a_idx'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='patients.invoice'),
        ),
    ]
