# Generated by Django 4.2.29 on 2026-05-14 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_squashed_0013_invoiceitem_appointment_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('data_sharing', 'External Data Sharing (NHIS/GHS)'), ('ai_analysis', 'Clinical AI Analysis'), ('research', 'Anonymized Research'), ('marketing', 'Communications/Marketing')], max_length=50)),
                ('is_granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('witness_name', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patients.patient')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'consent_type'], name='patients_pa_patient_1581f6_idx')],
                'unique_together': {('patient', 'consent_type')},
            },
        ),
    ]
