# Generated by Django 4.2.29 on 2026-05-22 22:39

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_patientconsent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=django_cryptography.fields.encrypt(models.DateField()),
        ),
        migrations.AlterField(
            model_name='patient',
            name='passport_number',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=50, null=True)),
        ),
    ]
