# Generated by Django 4.2.29 on 2026-06-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
    ]
