# Generated by Django 4.2.29 on 2026-06-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_remove_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientconsent',
            name='consent_type',
            field=models.CharField(choices=[('data_sharing', 'External Data Sharing (NHIS/GHS)'), ('research', 'Anonymized Research'), ('marketing', 'Communications/Marketing')], max_length=50),
        ),
    ]
