# Generated by Django 4.2.29 on 2026-06-25 13:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_invoice_paid_amount_to_cents'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appointment',
            managers=[
                ('tenant_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='clinicalalert',
            managers=[
                ('tenant_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='invoice',
            managers=[
                ('tenant_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='patientadmission',
            managers=[
                ('tenant_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
