# Generated by Django 6.0.2 on 2026-03-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('VIEW', 'View'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DEACTIVATE', 'Deactivate'), ('EXPORT', 'Export'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('ROLE_CHANGE', 'Role Change'), ('INVITE_SENT', 'Invite Sent'), ('ACCOUNT_ACTIVATED', 'Account Activated'), ('EMERGENCY_ACCESS', 'Emergency Access'), ('CROSS_FACILITY_ACCESS_REVOKED', 'Cross-Facility Access Revoked'), ('BULK_IMPORT', 'Bulk Import')], max_length=30),
        ),
    ]
