# Generated by Django 6.0.2 on 2026-03-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hie_shared_record_access_consent_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('hospital_admin', 'Hospital Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('lab_technician', 'Lab Technician')], max_length=20),
        ),
    ]
