# Generated by Django 6.0.2 on 2026-03-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blueprint_alerts_encounters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='chain_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
