# Generated by Django 4.2.29 on 2026-03-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_workflow_department_lab_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('VIEW', 'View'), ('VIEW_PATIENT_RECORD', 'View Patient Record'), ('VIEW_CROSS_FACILITY_RECORD', 'View Cross-Facility Record'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DEACTIVATE', 'Deactivate'), ('EXPORT', 'Export'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('ROLE_CHANGE', 'Role Change'), ('INVITE_SENT', 'Invite Sent'), ('ACCOUNT_ACTIVATED', 'Account Activated'), ('EMERGENCY_ACCESS', 'Emergency Access'), ('CROSS_FACILITY_ACCESS_REVOKED', 'Cross-Facility Access Revoked'), ('BULK_IMPORT', 'Bulk Import')], max_length=30),
        ),
    ]
