# Generated by Django 4.2.29 on 2026-03-07 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userpasswordhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperAdminHospitalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, help_text='Who granted this access (another super_admin or system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
                ('super_admin', models.ForeignKey(limit_choices_to={'role': 'super_admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Super Admin Hospital Access',
                'unique_together': {('super_admin', 'hospital')},
            },
        ),
    ]
