# Generated by Django 4.2.29 on 2026-03-08 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_phase7_password_recovery'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFASession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'MFA Session',
                'verbose_name_plural': 'MFA Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='passwordresetaudit',
            new_name='core_passwo_user_id_775cb9_idx',
            old_name='core_passwor_user_id_token_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetaudit',
            new_name='core_passwo_hospita_6da16b_idx',
            old_name='core_passwor_hospita_token_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetaudit',
            new_name='core_passwo_status_986040_idx',
            old_name='core_passwor_status_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('VIEW', 'View'), ('VIEW_PATIENT_RECORD', 'View Patient Record'), ('VIEW_CROSS_FACILITY_RECORD', 'View Cross-Facility Record'), ('CREATE', 'Create'), ('UPDATE', 'Update'), ('DEACTIVATE', 'Deactivate'), ('EXPORT', 'Export'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('ROLE_CHANGE', 'Role Change'), ('INVITE_SENT', 'Invite Sent'), ('ACCOUNT_ACTIVATED', 'Account Activated'), ('EMERGENCY_ACCESS', 'Emergency Access'), ('CROSS_FACILITY_ACCESS_REVOKED', 'Cross-Facility Access Revoked'), ('BULK_IMPORT', 'Bulk Import'), ('VIEW_AS_HOSPITAL', 'View As Hospital'), ('permission_denied', 'Permission Denied')], max_length=30),
        ),
        migrations.AddField(
            model_name='mfasession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
