# Generated by Django 4.2.29 on 2026-03-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='signature',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetaudit',
            name='failed_validation_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordresetaudit',
            name='link_clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetaudit',
            name='reset_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='chain_hash',
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='resource_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='passwordresetaudit',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hospital'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-timestamp'], name='core_auditl_user_id_2a1528_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['hospital', '-timestamp'], name='core_auditl_hospita_60127c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-timestamp'], name='core_auditl_action_f07419_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'hospital', '-timestamp'], name='core_auditl_action_f2b97d_idx'),
        ),
    ]
