# Generated by Django 4.2.29 on 2026-03-18 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auditlog_signature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupCodeRateLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_count', models.IntegerField(default=0)),
                ('first_attempt_at', models.DateTimeField(auto_now_add=True)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_code_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Code Rate Limit',
                'verbose_name_plural': 'Backup Code Rate Limits',
                'indexes': [models.Index(fields=['user', '-last_attempt_at'], name='core_backup_user_id_fe33e6_idx')],
            },
        ),
    ]
