# Generated by Django 4.2.29 on 2026-03-24 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_backupcoderatelimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('task_type', models.CharField(choices=[('export_pdf', 'PDF Export'), ('ai_analysis', 'AI Analysis'), ('risk_prediction', 'Risk Prediction'), ('mark_no_shows', 'Mark No Shows'), ('other', 'Other')], default='other', max_length=20)),
                ('resource_type', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['user', '-submitted_at'], name='core_tasksu_user_id_914882_idx'), models.Index(fields=['hospital', '-submitted_at'], name='core_tasksu_hospita_734822_idx'), models.Index(fields=['task_type', '-submitted_at'], name='core_tasksu_task_ty_db66d6_idx'), models.Index(fields=['-expires_at'], name='core_tasksu_expires_c5ae38_idx')],
            },
        ),
    ]
