# Generated by Cursor on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_tasksubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="superadminhospitalaccess",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

