# Generated by Django 4.2.29 on 2026-03-27 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_mfasession_email_otp_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_role_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
