# Generated by Django 4.2.29 on 2026-03-27 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_last_role_reviewed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MFAFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_failures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MFA Failure',
                'verbose_name_plural': 'MFA Failures',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_mfafai_user_id_dbda3a_idx')],
            },
        ),
    ]
