# Generated by Django 4.2.29 on 2026-04-06 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_add_password_reset_attempt_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(help_text='Client public key', max_length=100)),
                ('auth', models.CharField(help_text='Auth secret', max_length=50)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_push_subscription',
            },
        ),
        migrations.RenameIndex(
            model_name='passwordresetattempt',
            new_name='core_passwo_email_05f693_idx',
            old_name='core_passwor_email_cb02e7_idx',
        ),
        migrations.AddField(
            model_name='hospital',
            name='ai_enabled',
            field=models.BooleanField(default=True, help_text='Enable/disable AI features for this hospital'),
        ),
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=32, null=True)),
        ),
        migrations.AddField(
            model_name='userpushsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userpushsubscription',
            index=models.Index(fields=['user', 'is_active'], name='user_push_s_user_id_dba984_idx'),
        ),
    ]
