# Generated by Django 4.2.29 on 2026-04-19 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPasskey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_id', models.BinaryField(db_index=True, unique=True)),
                ('public_key', models.BinaryField()),
                ('sign_count', models.IntegerField(default=0)),
                ('device_name', models.CharField(blank=True, default='', max_length=100)),
                ('transports', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Passkey',
                'verbose_name_plural': 'User Passkeys',
                'indexes': [models.Index(fields=['user', 'credential_id'], name='core_userpa_user_id_8c3488_idx'), models.Index(fields=['user', '-last_used_at'], name='core_userpa_user_id_d8b246_idx')],
            },
        ),
    ]
