# Generated by Django 4.2.29 on 2026-04-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_userpasskey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpasskey',
            name='is_synced',
            field=models.BooleanField(default=False, help_text='True if synced via Apple/Google/Microsoft'),
        ),
        migrations.AddField(
            model_name='userpasskey',
            name='last_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpasskey',
            name='platform',
            field=models.CharField(choices=[('windows', 'Windows'), ('macos', 'macOS'), ('linux', 'Linux'), ('android', 'Android'), ('ios', 'iOS'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddIndex(
            model_name='userpasskey',
            index=models.Index(fields=['user', 'platform'], name='core_userpa_user_id_463044_idx'),
        ),
    ]
