# Generated by Django 4.2.29 on 2026-04-21 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_ai_deployment_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='archive_reason',
            field=models.CharField(blank=True, help_text='Reason for archival', max_length=500),
        ),
        migrations.AddField(
            model_name='hospital',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When hospital was archived', null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='archived_by',
            field=models.ForeignKey(blank=True, help_text='Super admin who initiated archival', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospital',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Soft-delete: hospital marked for archival but not hard-deleted'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['is_archived', 'is_active'], name='core_hospit_is_arch_fe51e2_idx'),
        ),
    ]
