# Generated by Django 4.2.29 on 2026-04-24 14:25

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_hospital_archive_reason_hospital_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='chain_hash',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='signature',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='mfa_backup_codes',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, null=True)),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('hospital_admin', 'Hospital Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('lab_technician', 'Lab Technician'), ('pharmacy_technician', 'Pharmacy Technician'), ('radiology_technician', 'Radiology Technician'), ('billing_staff', 'Billing Staff'), ('ward_clerk', 'Ward Clerk')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['hospital', 'role', 'account_status'], name='core_user_hospita_da3509_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='core_user_role_73872d_idx'),
        ),
    ]
