# Generated by Django 4.2.29 on 2026-05-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_auditlog_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('hospital_admin', 'Hospital Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('lab_technician', 'Lab Technician'), ('pharmacy_technician', 'Pharmacy Technician'), ('radiology_technician', 'Radiology Technician'), ('billing_staff', 'Billing Staff'), ('ward_clerk', 'Ward Clerk'), ('patient', 'Patient')], max_length=20),
        ),
    ]
