# Generated by Django 4.2.29 on 2026-05-27 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='mfa_method',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('email_otp', 'Email OTP'), ('step_up', 'Step-Up MFA'), ('totp', 'TOTP Authenticator')], help_text='Authentication factor method used for this action', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='risk_tier',
            field=models.IntegerField(blank=True, choices=[(1, 'AAL1: Trusted'), (2, 'AAL2: MFA'), (3, 'AAL3: Step-Up')], help_text='Authentication Assurance Level: 1=no MFA, 2=email OTP, 3=step-up required', null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ip_subnets',
            field=models.JSONField(blank=True, default=list, help_text="List of CIDR ranges for hospital network (e.g., ['192.168.1.0/24'])"),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('hospital_admin', 'Hospital Admin'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('receptionist', 'Receptionist'), ('lab_technician', 'Lab Technician'), ('pharmacy_technician', 'Pharmacy Technician'), ('radiology_technician', 'Radiology Technician'), ('billing_staff', 'Billing Staff'), ('ward_clerk', 'Ward Clerk')], max_length=20),
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_fingerprint', models.CharField(db_index=True, help_text='SHA256 fingerprint of device', max_length=64)),
                ('device_label', models.CharField(blank=True, help_text="Optional user-given device name (e.g., 'Main Office Desktop')", max_length=200)),
                ('last_verified_at', models.DateTimeField(auto_now=True, help_text='Last successful auth from this device')),
                ('expires_at', models.DateTimeField(help_text='Device trust expires after 30 days of inactivity')),
                ('is_active', models.BooleanField(default=True, help_text='User can revoke devices')),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent header from device')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Last known IP from this device', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='core_truste_user_id_81faf7_idx'), models.Index(fields=['expires_at'], name='core_truste_expires_8f9114_idx')],
                'unique_together': {('user', 'device_fingerprint')},
            },
        ),
        migrations.CreateModel(
            name='StepUpSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_token', models.CharField(help_text='Token linking request to OTP verification', max_length=128, unique=True)),
                ('otp_code', models.CharField(help_text='6-digit OTP sent to user email', max_length=6)),
                ('otp_hash', models.CharField(help_text='SHA256 hash of OTP (never store plaintext)', max_length=64)),
                ('action', models.CharField(help_text="Action type (e.g., 'cross_facility_access', 'break_glass', 'consent_grant')", max_length=50)),
                ('is_verified', models.BooleanField(default=False, help_text='True after OTP verification')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When OTP was verified', null=True)),
                ('expires_at', models.DateTimeField(help_text='Session expires after 5 minutes')),
                ('attempts', models.IntegerField(default=0, help_text='Failed OTP attempts (max 3)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_up_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'action'], name='core_stepup_user_id_289755_idx'), models.Index(fields=['expires_at'], name='core_stepup_expires_e154b9_idx')],
            },
        ),
    ]
