# Generated by Django 4.2.29 on 2026-05-27 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_add_device_trust_and_step_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCookie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cookie_token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('access_token_jwt', models.TextField()),
                ('refresh_token_jwt', models.TextField()),
                ('device_fingerprint', models.CharField(blank=True, max_length=256, null=True)),
                ('client_metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(auto_now=True)),
                ('is_revoked', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_cookies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Cookie Session',
                'verbose_name_plural': 'Client Cookie Sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_revoked'], name='core_client_user_id_448852_idx'), models.Index(fields=['cookie_token', 'is_revoked'], name='core_client_cookie__53b391_idx'), models.Index(fields=['expires_at'], name='core_client_expires_b4e3be_idx'), models.Index(fields=['-created_at'], name='core_client_created_d51da6_idx')],
            },
        ),
    ]
