# Generated by Django 4.2.29 on 2026-06-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='facility_type',
            field=models.CharField(choices=[('CHPS', 'CHPS'), ('HEALTH_CENTRE', 'Health Centre'), ('DISTRICT_HOSPITAL', 'District Hospital'), ('REGIONAL_HOSPITAL', 'Regional Hospital'), ('TEACHING_HOSPITAL', 'Teaching Hospital')], default='HEALTH_CENTRE', help_text='Ghana referral hierarchy level', max_length=50),
        ),
    ]
