# Generated by Django 4.2.29 on 2026-06-23 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_hospital_facility_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpushsubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='TaskSubmission',
        ),
        migrations.DeleteModel(
            name='UserPushSubscription',
        ),
    ]
