# Generated by Django 4.2.29 on 2026-06-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_hospital_facility_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trusteddevice',
            name='pin_hash',
            field=models.CharField(blank=True, help_text='Bcrypt hash of 4-digit PIN + user_id_salt', max_length=128, null=True),
        ),
    ]
