# Generated by Django 4.2.29 on 2026-06-10 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_auditlog_action_alter_tasksubmission_task_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPushSubscription',
        ),
    ]
